import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */
import {
  type ModelsTag,
  type ModelsUpdateUserOrganisation,
  type ModelsUser,
} from '../../lasius'
/**
 * @summary Remove current user's membership from selected organisation
 */
export function useDeleteUserMembershipByOrganisation(
  options?: ApiProxyOptions<void>,
) {
  return useApiProxy<void, undefined, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/user-organisations/organisations/${orgId}/leave`,
      method: 'DELETE',
    },
    options,
  )
} /**
 * @summary Get tags by organisation and project
 */
export function useGetTagsByProject(options?: ApiProxyOptions<ModelsTag[]>) {
  return useApiProxy<
    ModelsTag[],
    undefined,
    { orgId: string; projectId: string }
  >(
    {
      getUrl: ({ orgId, projectId }) =>
        `/user-organisations/organisations/${orgId}/projects/${projectId}/tags`,
      method: 'GET',
    },
    options,
  )
} /**
 * @summary Change current user's working hours for the selected organisation
 */
export function useUpdateWorkingHoursByOrganisation(
  options?: ApiProxyOptions<ModelsUser>,
) {
  return useApiProxy<
    ModelsUser,
    ModelsUpdateUserOrganisation,
    { orgId: string }
  >(
    {
      getUrl: ({ orgId }) =>
        `/user-organisations/organisations/${orgId}/working-hours`,
      method: 'POST',
    },
    options,
  )
}
