import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'

/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import { type CreateWsTicket200 } from '../../lasius'
/**
 * Generates a single-use ticket (60s TTL) for WebSocket authentication. Requires authenticated user.
 * @summary Create a short-lived WebSocket authentication ticket
 */
export function useCreateWsTicket(
  options?: ApiProxyOptions<CreateWsTicket200>,
) {
  return useApiProxy<CreateWsTicket200>(
    {
      getUrl: () => `/auth/ws-ticket`,
      method: 'POST',
    },
    options,
  )
}
