/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type {
  ModelsCreateProject,
  ModelsInvitationResult,
  ModelsProject,
  ModelsUpdateProject,
  ModelsUserStub,
  ModelsUserToProjectAssignment,
} from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
export function useGetProjectList(options?: ApiProxyOptions<ModelsProject[]>) {
  return useApiProxy<ModelsProject[], undefined, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/organisations/${orgId}/projects`,
      method: 'GET',
    },
    options,
  )
}
export function useCreateProject(options?: ApiProxyOptions<ModelsProject>) {
  return useApiProxy<ModelsProject, ModelsCreateProject, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/organisations/${orgId}/projects`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary update a project
 */
export function useUpdateProject(options?: ApiProxyOptions<ModelsProject>) {
  return useApiProxy<ModelsProject, ModelsUpdateProject, { orgId: string; projectId: string }>(
    {
      getUrl: ({ orgId, projectId }) => `/organisations/${orgId}/projects/${projectId}`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary Deactivate a project
 */
export function useDeactivateProject(options?: ApiProxyOptions<void>) {
  return useApiProxy<void, undefined, { orgId: string; projectId: string }>(
    {
      getUrl: ({ orgId, projectId }) => `/organisations/${orgId}/projects/${projectId}`,
      method: 'DELETE',
    },
    options,
  )
}
export function useGetProjectUserList(options?: ApiProxyOptions<ModelsUserStub[]>) {
  return useApiProxy<ModelsUserStub[], undefined, { orgId: string; projectId: string }>(
    {
      getUrl: ({ orgId, projectId }) => `/organisations/${orgId}/projects/${projectId}/users`,
      method: 'GET',
    },
    options,
  )
}
export function useInviteProjectUser(options?: ApiProxyOptions<ModelsInvitationResult>) {
  return useApiProxy<
    ModelsInvitationResult,
    ModelsUserToProjectAssignment,
    { orgId: string; projectId: string }
  >(
    {
      getUrl: ({ orgId, projectId }) => `/organisations/${orgId}/projects/${projectId}/users`,
      method: 'POST',
    },
    options,
  )
} /**
 * Get last activity date for a project.
 */
export function useGetProjectLastActivityDate(options?: ApiProxyOptions<string | void>) {
  return useApiProxy<string | void, undefined, { orgId: string; projectId: string }>(
    {
      getUrl: ({ orgId, projectId }) =>
        `/organisations/${orgId}/projects/${projectId}/last-activity`,
      method: 'GET',
    },
    options,
  )
}
export function useRemoveProjectUser(options?: ApiProxyOptions<void>) {
  return useApiProxy<void, undefined, { orgId: string; projectId: string; userId: string }>(
    {
      getUrl: ({ orgId, projectId, userId }) =>
        `/organisations/${orgId}/projects/${projectId}/users/${userId}`,
      method: 'DELETE',
    },
    options,
  )
} /**
 * @summary Remove current user's membership from selected project and selected organisation
 */
export function useRemoveProjectOwnUser(options?: ApiProxyOptions<void>) {
  return useApiProxy<void, undefined, { orgId: string; projectId: string }>(
    {
      getUrl: ({ orgId, projectId }) => `/organisations/${orgId}/projects/${projectId}/leave`,
      method: 'DELETE',
    },
    options,
  )
}
