/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type {
  GetOrganisationBookingAggregatedStatsParams,
  GetOrganisationBookingListParams,
  ModelsBooking,
  ModelsBookingStats,
} from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
/**
 * @summary Get bookings for the selected organisation within the selected timeframe
 */
function getGetOrganisationBookingListUrl(
  orgId: string,
  params?: GetOrganisationBookingListParams,
) {
  const normalizedParams = new URLSearchParams()
  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })
  const query = normalizedParams.toString()
  return query
    ? `/organisation-bookings/organisations/${orgId}/bookings/history` + '?' + query
    : `/organisation-bookings/organisations/${orgId}/bookings/history`
}

export function useGetOrganisationBookingList(options?: ApiProxyOptions<ModelsBooking[]>) {
  return useApiProxy<
    ModelsBooking[],
    undefined,
    { orgId: string; params?: GetOrganisationBookingListParams }
  >(
    {
      getUrl: ({ orgId, params }) => getGetOrganisationBookingListUrl(orgId, params),
      method: 'GET',
    },
    options,
  )
} /**
 * @summary Get aggregated statistics about bookings for the selected organisation within the selected timeframe
 */
function getGetOrganisationBookingAggregatedStatsUrl(
  orgId: string,
  params?: GetOrganisationBookingAggregatedStatsParams,
) {
  const normalizedParams = new URLSearchParams()
  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })
  const query = normalizedParams.toString()
  return query
    ? `/organisation-bookings/organisations/${orgId}/bookings/stats/aggregated` + '?' + query
    : `/organisation-bookings/organisations/${orgId}/bookings/stats/aggregated`
}

export function useGetOrganisationBookingAggregatedStats(
  options?: ApiProxyOptions<ModelsBookingStats[]>,
) {
  return useApiProxy<
    ModelsBookingStats[],
    undefined,
    { orgId: string; params?: GetOrganisationBookingAggregatedStatsParams }
  >(
    {
      getUrl: ({ orgId, params }) => getGetOrganisationBookingAggregatedStatsUrl(orgId, params),
      method: 'GET',
    },
    options,
  )
}
