compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0007
    level: discard
  - code: YN0013
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard

nmMode: hardlinks-local

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.1.cjs
