/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsApplicationConfig, ModelsCsrfToken } from './..'

import { lasiusFetch } from '../../lasius-fetch-instance.ts'

export type getConfigurationResponse200 = {
  data: ModelsApplicationConfig
  status: 200
}

export type getConfigurationResponseSuccess = getConfigurationResponse200 & {
  headers: Headers
}
export type getConfigurationResponse = getConfigurationResponseSuccess

export const getGetConfigurationUrl = () => {
  return `/config`
}

/**
 * @summary Get application config
 */
export const getConfiguration = async (
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<getConfigurationResponse> => {
  return lasiusFetch<getConfigurationResponse>(getGetConfigurationUrl(), {
    ...options,
    method: 'GET',
  })
}

export type getCsrfTokenResponse200 = {
  data: ModelsCsrfToken
  status: 200
}

export type getCsrfTokenResponseSuccess = getCsrfTokenResponse200 & {
  headers: Headers
}
export type getCsrfTokenResponse = getCsrfTokenResponseSuccess

export const getGetCsrfTokenUrl = () => {
  return `/csrf-token`
}

/**
 * @summary Get csrf token
 */
export const getCsrfToken = async (
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<getCsrfTokenResponse> => {
  return lasiusFetch<getCsrfTokenResponse>(getGetCsrfTokenUrl(), {
    ...options,
    method: 'GET',
  })
}
