/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsFavoritesRequest, ModelsUserFavorites } from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
/**
 * @summary Get current user's favorite bookings list for the selected organisation
 */
export function useGetFavoriteBookingList(options?: ApiProxyOptions<ModelsUserFavorites>) {
  return useApiProxy<ModelsUserFavorites, undefined, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/user-favorites/organisations/${orgId}`,
      method: 'GET',
    },
    options,
  )
} /**
 * @summary Save a new favorite booking for the current user in the selected organisation
 */
export function useAddFavoriteBooking(options?: ApiProxyOptions<ModelsUserFavorites[]>) {
  return useApiProxy<ModelsUserFavorites[], ModelsFavoritesRequest, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/user-favorites/organisations/${orgId}`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary Remove a favorite booking for the current user from the selected organisation
 */
export function useDeleteFavoriteBooking(options?: ApiProxyOptions<void>) {
  return useApiProxy<void, ModelsFavoritesRequest, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/user-favorites/organisations/${orgId}`,
      method: 'DELETE',
    },
    options,
  )
}
