/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsPersonalDataUpdate, ModelsUser } from './..'

import { lasiusFetch } from '../../lasius-fetch-instance.ts'

export type updateUserProfileByOrganisationResponse200 = {
  data: ModelsUser
  status: 200
}

export type updateUserProfileByOrganisationResponseSuccess =
  updateUserProfileByOrganisationResponse200 & {
    headers: Headers
  }
export type updateUserProfileByOrganisationResponse = updateUserProfileByOrganisationResponseSuccess

export const getUpdateUserProfileByOrganisationUrl = (orgId: string, userId: string) => {
  return `/users/organisations/${orgId}/users/${userId}`
}

/**
 * The email is read-only. A request with a changed email answers 400 with the body email_read_only.
 * @summary Change selected user's profile in selected organisation
 */
export const updateUserProfileByOrganisation = async (
  orgId: string,
  userId: string,
  modelsPersonalDataUpdate?: ModelsPersonalDataUpdate,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<updateUserProfileByOrganisationResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {}
    if (h instanceof Headers) return Object.fromEntries(h.entries())
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      )
    }
    const headers: Record<string, string | readonly string[]> = {}
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value
    }
    return headers
  }
  return lasiusFetch<updateUserProfileByOrganisationResponse>(
    getUpdateUserProfileByOrganisationUrl(orgId, userId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
      body: JSON.stringify(modelsPersonalDataUpdate),
    },
  )
}
