/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type {
  ModelsOAuthAuthorizationCodeLoginRequest,
  ModelsOAuthUser,
  ModelsOAuthUserId,
  ModelsOAuthUserRegistration,
  ModelsPasswordChangeRequest,
} from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
/**
 * @summary --------please annotate------
 */
export function useRegisterOAuthUser(options?: ApiProxyOptions<ModelsOAuthUserId>) {
  return useApiProxy<ModelsOAuthUserId, ModelsOAuthUserRegistration>(
    {
      getUrl: () => `/oauth2/user/register`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary Change current user's password
 */
export function useUpdateUserPassword(options?: ApiProxyOptions<void>) {
  return useApiProxy<void, ModelsPasswordChangeRequest>(
    {
      getUrl: () => `/oauth2/user/update-password`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary access to internally provided oauth2 provider. Use for demo purposes only!
 */
export function useOauthAccessToken(options?: ApiProxyOptions<void>) {
  return useApiProxy<void>(
    {
      getUrl: () => `/oauth2/access_token`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary login to the oauth provider with the authorization code flow
 */
export function useLogin(options?: ApiProxyOptions<unknown>) {
  return useApiProxy<unknown, ModelsOAuthAuthorizationCodeLoginRequest>(
    {
      getUrl: () => `/oauth2/login`,
      method: 'POST',
      skipAuth: true,
    },
    options,
  )
} /**
 * @summary logout from the internal oauth provider, token will not be valid anymore afterwards
 */
export function useLogout(options?: ApiProxyOptions<void>) {
  return useApiProxy<void>(
    {
      getUrl: () => `/oauth2/logout`,
      method: 'POST',
      skipAuth: true,
    },
    options,
  )
} /**
 * @summary access to internally provided oauth2 provider. Use for demo purposes only!
 */
export function useGetUOAuthUserProfile(options?: ApiProxyOptions<ModelsOAuthUser>) {
  return useApiProxy<ModelsOAuthUser>(
    {
      getUrl: () => `/oauth2/profile`,
      method: 'GET',
    },
    options,
  )
}
