/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { ModelsPersonalDataUpdate, ModelsUser } from './..'

import { lasiusFetch } from '../../lasius-fetch-instance'

/**
 * @summary Change selected user's profile in selected organisation
 */
export type updateUserProfileByOrganisationResponse200 = {
  data: ModelsUser
  status: 200
}

export type updateUserProfileByOrganisationResponseSuccess =
  updateUserProfileByOrganisationResponse200 & {
    headers: Headers
  }
export type updateUserProfileByOrganisationResponse =
  updateUserProfileByOrganisationResponseSuccess

export const getUpdateUserProfileByOrganisationUrl = (
  orgId: string,
  userId: string,
) => {
  return `/users/organisations/${orgId}/users/${userId}`
}

export const updateUserProfileByOrganisation = async (
  orgId: string,
  userId: string,
  modelsPersonalDataUpdate: ModelsPersonalDataUpdate,
  options?: RequestInit,
): Promise<updateUserProfileByOrganisationResponse> => {
  return lasiusFetch<updateUserProfileByOrganisationResponse>(
    getUpdateUserProfileByOrganisationUrl(orgId, userId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsPersonalDataUpdate),
    },
  )
}
