import { lasiusFetch } from '../../lasius-fetch-instance'
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type ModelsPersonalDataUpdate, type ModelsUser } from '.././'

export type updateUserProfileByOrganisationResponse =
	updateUserProfileByOrganisationResponseSuccess

/**
 * @summary Change selected user's profile in selected organisation
 */
export type updateUserProfileByOrganisationResponse200 = {
	data: ModelsUser
	status: 200
}

export type updateUserProfileByOrganisationResponseSuccess =
	updateUserProfileByOrganisationResponse200 & {
		headers: Headers
	}

export const getUpdateUserProfileByOrganisationUrl = (
	orgId: string,
	userId: string,
) => {
	return `/users/organisations/${orgId}/users/${userId}`
}

export const updateUserProfileByOrganisation = async (
	orgId: string,
	userId: string,
	modelsPersonalDataUpdate: ModelsPersonalDataUpdate,
	options?: RequestInit,
): Promise<updateUserProfileByOrganisationResponse> => {
	return lasiusFetch<updateUserProfileByOrganisationResponse>(
		getUpdateUserProfileByOrganisationUrl(orgId, userId),
		{
			...options,
			body: JSON.stringify(modelsPersonalDataUpdate),
			headers: { 'Content-Type': 'application/json', ...options?.headers },
			method: 'POST',
		},
	)
}
