/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type {
  ModelsCreateProject,
  ModelsInvitationResult,
  ModelsProject,
  ModelsUpdateProject,
  ModelsUserStub,
  ModelsUserToProjectAssignment,
} from './..'

import { lasiusFetch } from '../../lasius-fetch-instance.ts'

export type getProjectListResponse200 = {
  data: ModelsProject[]
  status: 200
}

export type getProjectListResponseSuccess = getProjectListResponse200 & {
  headers: Headers
}
export type getProjectListResponse = getProjectListResponseSuccess

export const getGetProjectListUrl = (orgId: string) => {
  return `/organisations/${orgId}/projects`
}

export const getProjectList = async (
  orgId: string,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<getProjectListResponse> => {
  return lasiusFetch<getProjectListResponse>(getGetProjectListUrl(orgId), {
    ...options,
    method: 'GET',
  })
}

export type createProjectResponse201 = {
  data: ModelsProject
  status: 201
}

export type createProjectResponseSuccess = createProjectResponse201 & {
  headers: Headers
}
export type createProjectResponse = createProjectResponseSuccess

export const getCreateProjectUrl = (orgId: string) => {
  return `/organisations/${orgId}/projects`
}

export const createProject = async (
  orgId: string,
  modelsCreateProject?: ModelsCreateProject,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<createProjectResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {}
    if (h instanceof Headers) return Object.fromEntries(h.entries())
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      )
    }
    const headers: Record<string, string | readonly string[]> = {}
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value
    }
    return headers
  }
  return lasiusFetch<createProjectResponse>(getCreateProjectUrl(orgId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(modelsCreateProject),
  })
}

export type updateProjectResponse200 = {
  data: ModelsProject
  status: 200
}

export type updateProjectResponseSuccess = updateProjectResponse200 & {
  headers: Headers
}
export type updateProjectResponse = updateProjectResponseSuccess

export const getUpdateProjectUrl = (orgId: string, projectId: string) => {
  return `/organisations/${orgId}/projects/${projectId}`
}

/**
 * @summary update a project
 */
export const updateProject = async (
  orgId: string,
  projectId: string,
  modelsUpdateProject?: ModelsUpdateProject,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<updateProjectResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {}
    if (h instanceof Headers) return Object.fromEntries(h.entries())
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      )
    }
    const headers: Record<string, string | readonly string[]> = {}
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value
    }
    return headers
  }
  return lasiusFetch<updateProjectResponse>(getUpdateProjectUrl(orgId, projectId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(modelsUpdateProject),
  })
}

export type deactivateProjectResponse200 = {
  data: void
  status: 200
}

export type deactivateProjectResponseSuccess = deactivateProjectResponse200 & {
  headers: Headers
}
export type deactivateProjectResponse = deactivateProjectResponseSuccess

export const getDeactivateProjectUrl = (orgId: string, projectId: string) => {
  return `/organisations/${orgId}/projects/${projectId}`
}

/**
 * @summary Deactivate a project
 */
export const deactivateProject = async (
  orgId: string,
  projectId: string,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<deactivateProjectResponse> => {
  return lasiusFetch<deactivateProjectResponse>(getDeactivateProjectUrl(orgId, projectId), {
    ...options,
    method: 'DELETE',
  })
}

export type getProjectUserListResponse200 = {
  data: ModelsUserStub[]
  status: 200
}

export type getProjectUserListResponseSuccess = getProjectUserListResponse200 & {
  headers: Headers
}
export type getProjectUserListResponse = getProjectUserListResponseSuccess

export const getGetProjectUserListUrl = (orgId: string, projectId: string) => {
  return `/organisations/${orgId}/projects/${projectId}/users`
}

export const getProjectUserList = async (
  orgId: string,
  projectId: string,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<getProjectUserListResponse> => {
  return lasiusFetch<getProjectUserListResponse>(getGetProjectUserListUrl(orgId, projectId), {
    ...options,
    method: 'GET',
  })
}

export type inviteProjectUserResponse201 = {
  data: ModelsInvitationResult
  status: 201
}

export type inviteProjectUserResponseSuccess = inviteProjectUserResponse201 & {
  headers: Headers
}
export type inviteProjectUserResponse = inviteProjectUserResponseSuccess

export const getInviteProjectUserUrl = (orgId: string, projectId: string) => {
  return `/organisations/${orgId}/projects/${projectId}/users`
}

export const inviteProjectUser = async (
  orgId: string,
  projectId: string,
  modelsUserToProjectAssignment?: ModelsUserToProjectAssignment,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<inviteProjectUserResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {}
    if (h instanceof Headers) return Object.fromEntries(h.entries())
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      )
    }
    const headers: Record<string, string | readonly string[]> = {}
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value
    }
    return headers
  }
  return lasiusFetch<inviteProjectUserResponse>(getInviteProjectUserUrl(orgId, projectId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(modelsUserToProjectAssignment),
  })
}

export type getProjectLastActivityDateResponse200 = {
  data: string
  status: 200
}

export type getProjectLastActivityDateResponse204 = {
  data: void
  status: 204
}

export type getProjectLastActivityDateResponseSuccess = (
  getProjectLastActivityDateResponse200 | getProjectLastActivityDateResponse204
) & {
  headers: Headers
}
export type getProjectLastActivityDateResponse = getProjectLastActivityDateResponseSuccess

export const getGetProjectLastActivityDateUrl = (orgId: string, projectId: string) => {
  return `/organisations/${orgId}/projects/${projectId}/last-activity`
}

/**
 * Get last activity date for a project.
 */
export const getProjectLastActivityDate = async (
  orgId: string,
  projectId: string,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<getProjectLastActivityDateResponse> => {
  return lasiusFetch<getProjectLastActivityDateResponse>(
    getGetProjectLastActivityDateUrl(orgId, projectId),
    {
      ...options,
      method: 'GET',
    },
  )
}

export type removeProjectUserResponse200 = {
  data: void
  status: 200
}

export type removeProjectUserResponseSuccess = removeProjectUserResponse200 & {
  headers: Headers
}
export type removeProjectUserResponse = removeProjectUserResponseSuccess

export const getRemoveProjectUserUrl = (orgId: string, projectId: string, userId: string) => {
  return `/organisations/${orgId}/projects/${projectId}/users/${userId}`
}

export const removeProjectUser = async (
  orgId: string,
  projectId: string,
  userId: string,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<removeProjectUserResponse> => {
  return lasiusFetch<removeProjectUserResponse>(getRemoveProjectUserUrl(orgId, projectId, userId), {
    ...options,
    method: 'DELETE',
  })
}

export type removeProjectOwnUserResponse200 = {
  data: void
  status: 200
}

export type removeProjectOwnUserResponseSuccess = removeProjectOwnUserResponse200 & {
  headers: Headers
}
export type removeProjectOwnUserResponse = removeProjectOwnUserResponseSuccess

export const getRemoveProjectOwnUserUrl = (orgId: string, projectId: string) => {
  return `/organisations/${orgId}/projects/${projectId}/leave`
}

/**
 * @summary Remove current user's membership from selected project and selected organisation
 */
export const removeProjectOwnUser = async (
  orgId: string,
  projectId: string,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<removeProjectOwnUserResponse> => {
  return lasiusFetch<removeProjectOwnUserResponse>(getRemoveProjectOwnUserUrl(orgId, projectId), {
    ...options,
    method: 'DELETE',
  })
}
