import { useApiProxy } from '~/hooks/use-api-proxy'

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import {
	type ModelsOAuthAuthorizationCodeLoginRequest,
	type ModelsOAuthUser,
	type ModelsOAuthUserId,
	type ModelsOAuthUserRegistration,
	type ModelsPasswordChangeRequest,
} from '../../lasius'
/**
 * @summary access to internally provided oauth2 provider. Use for demo purposes only!
 */
export function useGetUOAuthUserProfile() {
	return useApiProxy<ModelsOAuthUser>({
		getUrl: () => `/oauth2/profile`,
		method: 'GET',
	})
} /**
 * @summary login to the oauth provider with the authorization code flow
 */
export function useLogin() {
	return useApiProxy<unknown, ModelsOAuthAuthorizationCodeLoginRequest>({
		getUrl: () => `/oauth2/login`,
		method: 'POST',
		skipAuth: true,
	})
} /**
 * @summary logout from the internal oauth provider, token will not be valid anymore afterwards
 */
export function useLogout() {
	return useApiProxy<void>({
		getUrl: () => `/oauth2/logout`,
		method: 'POST',
		skipAuth: true,
	})
} /**
 * @summary access to internally provided oauth2 provider. Use for demo purposes only!
 */
export function useOauthAccessToken() {
	return useApiProxy<void>({
		getUrl: () => `/oauth2/access_token`,
		method: 'POST',
	})
} /**
 * @summary --------please annotate------
 */
export function useRegisterOAuthUser() {
	return useApiProxy<ModelsOAuthUserId, ModelsOAuthUserRegistration>({
		getUrl: () => `/oauth2/user/register`,
		method: 'POST',
	})
} /**
 * @summary Change current user's password
 */
export function useUpdateUserPassword() {
	return useApiProxy<void, ModelsPasswordChangeRequest>({
		getUrl: () => `/oauth2/user/update-password`,
		method: 'POST',
	})
}
