import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import {
  type ModelsOAuthAuthorizationCodeLoginRequest,
  type ModelsOAuthUser,
  type ModelsOAuthUserId,
  type ModelsOAuthUserRegistration,
  type ModelsPasswordChangeRequest,
} from '../../lasius'
/**
 * @summary access to internally provided oauth2 provider. Use for demo purposes only!
 */
export function useGetUOAuthUserProfile(
  options?: ApiProxyOptions<ModelsOAuthUser>,
) {
  return useApiProxy<ModelsOAuthUser>(
    {
      getUrl: () => `/oauth2/profile`,
      method: 'GET',
    },
    options,
  )
} /**
 * @summary login to the oauth provider with the authorization code flow
 */
export function useLogin(options?: ApiProxyOptions<unknown>) {
  return useApiProxy<unknown, ModelsOAuthAuthorizationCodeLoginRequest>(
    {
      getUrl: () => `/oauth2/login`,
      method: 'POST',
      skipAuth: true,
    },
    options,
  )
} /**
 * @summary logout from the internal oauth provider, token will not be valid anymore afterwards
 */
export function useLogout(options?: ApiProxyOptions<void>) {
  return useApiProxy<void>(
    {
      getUrl: () => `/oauth2/logout`,
      method: 'POST',
      skipAuth: true,
    },
    options,
  )
} /**
 * @summary access to internally provided oauth2 provider. Use for demo purposes only!
 */
export function useOauthAccessToken(options?: ApiProxyOptions<void>) {
  return useApiProxy<void>(
    {
      getUrl: () => `/oauth2/access_token`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary --------please annotate------
 */
export function useRegisterOAuthUser(
  options?: ApiProxyOptions<ModelsOAuthUserId>,
) {
  return useApiProxy<ModelsOAuthUserId, ModelsOAuthUserRegistration>(
    {
      getUrl: () => `/oauth2/user/register`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary Change current user's password
 */
export function useUpdateUserPassword(options?: ApiProxyOptions<void>) {
  return useApiProxy<void, ModelsPasswordChangeRequest>(
    {
      getUrl: () => `/oauth2/user/update-password`,
      method: 'POST',
    },
    options,
  )
}
