import { useApiProxy } from '~/hooks/use-api-proxy'

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import { type ModelsPersonalDataUpdate, type ModelsUser } from '../../lasius'
/**
 * @summary Change selected user's profile in selected organisation
 */
export function useUpdateUserProfileByOrganisation() {
	return useApiProxy<
		ModelsUser,
		ModelsPersonalDataUpdate,
		{ orgId: string; userId: string }
	>({
		getUrl: ({ orgId, userId }) =>
			`/users/organisations/${orgId}/users/${userId}`,
		method: 'POST',
	})
}
