import { lasiusFetch } from '../../lasius-fetch-instance'
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import {
	type ModelsAcceptTOSRequest,
	type ModelsPersonalDataUpdate,
	type ModelsUser,
	type ModelsUserSettings,
} from '.././'

export type getUserProfileResponse = getUserProfileResponseSuccess

/**
 * @summary Get current user's profile
 */
export type getUserProfileResponse200 = {
	data: ModelsUser
	status: 200
}

export type getUserProfileResponseSuccess = getUserProfileResponse200 & {
	headers: Headers
}

export const getGetUserProfileUrl = () => {
	return `/user/profile`
}

export const getUserProfile = async (
	options?: RequestInit,
): Promise<getUserProfileResponse> => {
	return lasiusFetch<getUserProfileResponse>(getGetUserProfileUrl(), {
		...options,
		method: 'GET',
	})
}

export type updateUserProfileResponse = updateUserProfileResponseSuccess

/**
 * @summary Change current user's profile
 */
export type updateUserProfileResponse200 = {
	data: ModelsUser
	status: 200
}

export type updateUserProfileResponseSuccess = updateUserProfileResponse200 & {
	headers: Headers
}

export const getUpdateUserProfileUrl = () => {
	return `/user/profile`
}

export const updateUserProfile = async (
	modelsPersonalDataUpdate: ModelsPersonalDataUpdate,
	options?: RequestInit,
): Promise<updateUserProfileResponse> => {
	return lasiusFetch<updateUserProfileResponse>(getUpdateUserProfileUrl(), {
		...options,
		body: JSON.stringify(modelsPersonalDataUpdate),
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		method: 'POST',
	})
}

export type updateUserSettingsResponse = updateUserSettingsResponseSuccess

/**
 * @summary Change current user's settings
 */
export type updateUserSettingsResponse200 = {
	data: ModelsUser
	status: 200
}

export type updateUserSettingsResponseSuccess =
	updateUserSettingsResponse200 & {
		headers: Headers
	}

export const getUpdateUserSettingsUrl = () => {
	return `/user/profile/settings`
}

export const updateUserSettings = async (
	modelsUserSettings: ModelsUserSettings,
	options?: RequestInit,
): Promise<updateUserSettingsResponse> => {
	return lasiusFetch<updateUserSettingsResponse>(getUpdateUserSettingsUrl(), {
		...options,
		body: JSON.stringify(modelsUserSettings),
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		method: 'POST',
	})
}

export type acceptUserTOSResponse = acceptUserTOSResponseSuccess

/**
 * @summary Accept terms of service (TOS)
 */
export type acceptUserTOSResponse200 = {
	data: ModelsUser
	status: 200
}

export type acceptUserTOSResponseSuccess = acceptUserTOSResponse200 & {
	headers: Headers
}

export const getAcceptUserTOSUrl = () => {
	return `/user/accept-tos`
}

export const acceptUserTOS = async (
	modelsAcceptTOSRequest: ModelsAcceptTOSRequest,
	options?: RequestInit,
): Promise<acceptUserTOSResponse> => {
	return lasiusFetch<acceptUserTOSResponse>(getAcceptUserTOSUrl(), {
		...options,
		body: JSON.stringify(modelsAcceptTOSRequest),
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		method: 'POST',
	})
}
