/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { CreateWsTicket200 } from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
/**
 * Generates a single-use ticket (60s TTL) for WebSocket authentication. Requires authenticated user.
 * @summary Create a short-lived WebSocket authentication ticket
 */
export function useCreateWsTicket(options?: ApiProxyOptions<CreateWsTicket200>) {
  return useApiProxy<CreateWsTicket200>(
    {
      getUrl: () => `/auth/ws-ticket`,
      method: 'POST',
    },
    options,
  )
}
