/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { ModelsApplicationConfig, ModelsCsrfToken } from '.././'

import { lasiusFetch } from '../../lasius-fetch-instance'

/**
 * @summary Get application config
 */
export type getConfigurationResponse200 = {
	data: ModelsApplicationConfig
	status: 200
}

export type getConfigurationResponseSuccess = getConfigurationResponse200 & {
	headers: Headers
}
export type getConfigurationResponse = getConfigurationResponseSuccess

export const getGetConfigurationUrl = () => {
	return `/config`
}

export const getConfiguration = async (
	options?: RequestInit,
): Promise<getConfigurationResponse> => {
	return lasiusFetch<getConfigurationResponse>(getGetConfigurationUrl(), {
		...options,
		method: 'GET',
	})
}

/**
 * @summary Get csrf token
 */
export type getCsrfTokenResponse200 = {
	data: ModelsCsrfToken
	status: 200
}

export type getCsrfTokenResponseSuccess = getCsrfTokenResponse200 & {
	headers: Headers
}
export type getCsrfTokenResponse = getCsrfTokenResponseSuccess

export const getGetCsrfTokenUrl = () => {
	return `/csrf-token`
}

export const getCsrfToken = async (
	options?: RequestInit,
): Promise<getCsrfTokenResponse> => {
	return lasiusFetch<getCsrfTokenResponse>(getGetCsrfTokenUrl(), {
		...options,
		method: 'GET',
	})
}
