/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type {
  DeleteConfig400,
  DeleteConfig403,
  DeleteConfig404,
  DeleteConfig409,
  GetConfigsParams,
  GetExternalProjectMetadata400,
  GetExternalProjectMetadataParams,
  ListGithubResourceOwners400,
  ListProjects400,
  ModelsCreateIssueImporterConfig,
  ModelsCreateProjectMapping,
  ModelsExternalProjectMetadata,
  ModelsIssueImporterConfigId,
  ModelsIssueImporterConfigResponse,
  ModelsListProjectsResponse,
  ModelsProjectMappingId,
  ModelsUpdateIssueImporterConfig,
  ModelsUpdateProjectMapping,
  RefreshTags202,
  RefreshTags404,
  TestConnectivity200,
  TestConnectivity400,
  TestExistingConfig200,
  TestExistingConfig400,
} from './..'

import { lasiusFetch } from '../../lasius-fetch-instance.ts'

export type getConfigsResponse200 = {
  data: ModelsIssueImporterConfigResponse[]
  status: 200
}

export type getConfigsResponse403 = {
  data: void
  status: 403
}

export type getConfigsResponseSuccess = getConfigsResponse200 & {
  headers: Headers
}
export type getConfigsResponseError = getConfigsResponse403 & {
  headers: Headers
}

export type getConfigsResponse = getConfigsResponseSuccess | getConfigsResponseError

export const getGetConfigsUrl = (orgId: string, params?: GetConfigsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/organisations/${orgId}/issue-importers?${stringifiedParams}`
    : `/organisations/${orgId}/issue-importers`
}

/**
 * @summary Get all importer configurations for organisation (optionally filtered by type)
 */
export const getConfigs = async (
  orgId: string,
  params?: GetConfigsParams,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<getConfigsResponse> => {
  return lasiusFetch<getConfigsResponse>(getGetConfigsUrl(orgId, params), {
    ...options,
    method: 'GET',
  })
}

export type createConfigResponse201 = {
  data: ModelsIssueImporterConfigResponse
  status: 201
}

export type createConfigResponse400 = {
  data: void
  status: 400
}

export type createConfigResponse403 = {
  data: void
  status: 403
}

export type createConfigResponseSuccess = createConfigResponse201 & {
  headers: Headers
}
export type createConfigResponseError = (createConfigResponse400 | createConfigResponse403) & {
  headers: Headers
}

export type createConfigResponse = createConfigResponseSuccess | createConfigResponseError

export const getCreateConfigUrl = (orgId: string) => {
  return `/organisations/${orgId}/issue-importers`
}

/**
 * @summary Create new importer configuration (Organisation Admin only)
 */
export const createConfig = async (
  orgId: string,
  modelsCreateIssueImporterConfig: ModelsCreateIssueImporterConfig,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<createConfigResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {}
    if (h instanceof Headers) return Object.fromEntries(h.entries())
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      )
    }
    const headers: Record<string, string | readonly string[]> = {}
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value
    }
    return headers
  }
  return lasiusFetch<createConfigResponse>(getCreateConfigUrl(orgId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(modelsCreateIssueImporterConfig),
  })
}

export type getConfigResponse200 = {
  data: ModelsIssueImporterConfigResponse
  status: 200
}

export type getConfigResponse403 = {
  data: void
  status: 403
}

export type getConfigResponse404 = {
  data: void
  status: 404
}

export type getConfigResponseSuccess = getConfigResponse200 & {
  headers: Headers
}
export type getConfigResponseError = (getConfigResponse403 | getConfigResponse404) & {
  headers: Headers
}

export type getConfigResponse = getConfigResponseSuccess | getConfigResponseError

export const getGetConfigUrl = (orgId: string, configId: ModelsIssueImporterConfigId) => {
  return `/organisations/${orgId}/issue-importers/${configId}`
}

/**
 * @summary Get importer configuration by ID
 */
export const getConfig = async (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<getConfigResponse> => {
  return lasiusFetch<getConfigResponse>(getGetConfigUrl(orgId, configId), {
    ...options,
    method: 'GET',
  })
}

export type updateConfigResponse200 = {
  data: ModelsIssueImporterConfigResponse
  status: 200
}

export type updateConfigResponse400 = {
  data: void
  status: 400
}

export type updateConfigResponse403 = {
  data: void
  status: 403
}

export type updateConfigResponse404 = {
  data: void
  status: 404
}

export type updateConfigResponseSuccess = updateConfigResponse200 & {
  headers: Headers
}
export type updateConfigResponseError = (
  updateConfigResponse400 | updateConfigResponse403 | updateConfigResponse404
) & {
  headers: Headers
}

export type updateConfigResponse = updateConfigResponseSuccess | updateConfigResponseError

export const getUpdateConfigUrl = (orgId: string, configId: ModelsIssueImporterConfigId) => {
  return `/organisations/${orgId}/issue-importers/${configId}`
}

/**
 * @summary Update importer configuration (Organisation Admin only)
 */
export const updateConfig = async (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  modelsUpdateIssueImporterConfig: ModelsUpdateIssueImporterConfig,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<updateConfigResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {}
    if (h instanceof Headers) return Object.fromEntries(h.entries())
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      )
    }
    const headers: Record<string, string | readonly string[]> = {}
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value
    }
    return headers
  }
  return lasiusFetch<updateConfigResponse>(getUpdateConfigUrl(orgId, configId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(modelsUpdateIssueImporterConfig),
  })
}

export type deleteConfigResponse204 = {
  data: void
  status: 204
}

export type deleteConfigResponse400 = {
  data: DeleteConfig400
  status: 400
}

export type deleteConfigResponse403 = {
  data: DeleteConfig403
  status: 403
}

export type deleteConfigResponse404 = {
  data: DeleteConfig404
  status: 404
}

export type deleteConfigResponse409 = {
  data: DeleteConfig409
  status: 409
}

export type deleteConfigResponseSuccess = deleteConfigResponse204 & {
  headers: Headers
}
export type deleteConfigResponseError = (
  | deleteConfigResponse400
  | deleteConfigResponse403
  | deleteConfigResponse404
  | deleteConfigResponse409
) & {
  headers: Headers
}

export type deleteConfigResponse = deleteConfigResponseSuccess | deleteConfigResponseError

export const getDeleteConfigUrl = (orgId: string, configId: ModelsIssueImporterConfigId) => {
  return `/organisations/${orgId}/issue-importers/${configId}`
}

/**
 * @summary Delete importer configuration (Organisation Admin only)
 */
export const deleteConfig = async (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<deleteConfigResponse> => {
  return lasiusFetch<deleteConfigResponse>(getDeleteConfigUrl(orgId, configId), {
    ...options,
    method: 'DELETE',
  })
}

export type getConfigForProjectResponse200 = {
  data: ModelsIssueImporterConfigResponse
  status: 200
}

export type getConfigForProjectResponse403 = {
  data: void
  status: 403
}

export type getConfigForProjectResponse404 = {
  data: void
  status: 404
}

export type getConfigForProjectResponseSuccess = getConfigForProjectResponse200 & {
  headers: Headers
}
export type getConfigForProjectResponseError = (
  getConfigForProjectResponse403 | getConfigForProjectResponse404
) & {
  headers: Headers
}

export type getConfigForProjectResponse =
  getConfigForProjectResponseSuccess | getConfigForProjectResponseError

export const getGetConfigForProjectUrl = (orgId: string, projectId: string) => {
  return `/organisations/${orgId}/projects/${projectId}/issue-importer`
}

/**
 * @summary Get importer configuration for a specific project
 */
export const getConfigForProject = async (
  orgId: string,
  projectId: string,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<getConfigForProjectResponse> => {
  return lasiusFetch<getConfigForProjectResponse>(getGetConfigForProjectUrl(orgId, projectId), {
    ...options,
    method: 'GET',
  })
}

export type testConnectivityResponse200 = {
  data: TestConnectivity200
  status: 200
}

export type testConnectivityResponse400 = {
  data: TestConnectivity400
  status: 400
}

export type testConnectivityResponseSuccess = testConnectivityResponse200 & {
  headers: Headers
}
export type testConnectivityResponseError = testConnectivityResponse400 & {
  headers: Headers
}

export type testConnectivityResponse =
  testConnectivityResponseSuccess | testConnectivityResponseError

export const getTestConnectivityUrl = (orgId: string) => {
  return `/organisations/${orgId}/issue-importers/test`
}

/**
 * Tests connectivity to GitLab/Jira/Plane without saving configuration. Useful for validating credentials before creating a config. Requires only OrganisationMember role since nothing is saved.
 * @summary Test connectivity to external service
 */
export const testConnectivity = async (
  orgId: string,
  modelsCreateIssueImporterConfig: ModelsCreateIssueImporterConfig,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<testConnectivityResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {}
    if (h instanceof Headers) return Object.fromEntries(h.entries())
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      )
    }
    const headers: Record<string, string | readonly string[]> = {}
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value
    }
    return headers
  }
  return lasiusFetch<testConnectivityResponse>(getTestConnectivityUrl(orgId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(modelsCreateIssueImporterConfig),
  })
}

export type testExistingConfigResponse200 = {
  data: TestExistingConfig200
  status: 200
}

export type testExistingConfigResponse400 = {
  data: TestExistingConfig400
  status: 400
}

export type testExistingConfigResponse403 = {
  data: void
  status: 403
}

export type testExistingConfigResponse404 = {
  data: void
  status: 404
}

export type testExistingConfigResponseSuccess = testExistingConfigResponse200 & {
  headers: Headers
}
export type testExistingConfigResponseError = (
  testExistingConfigResponse400 | testExistingConfigResponse403 | testExistingConfigResponse404
) & {
  headers: Headers
}

export type testExistingConfigResponse =
  testExistingConfigResponseSuccess | testExistingConfigResponseError

export const getTestExistingConfigUrl = (orgId: string, configId: ModelsIssueImporterConfigId) => {
  return `/organisations/${orgId}/issue-importers/${configId}/test`
}

/**
 * Tests connectivity to external service using credentials from an existing saved configuration. Useful for validating that saved credentials still work or testing after updating configuration. Requires only OrganisationMember role since nothing is modified.
 * @summary Test connectivity for existing configuration
 */
export const testExistingConfig = async (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<testExistingConfigResponse> => {
  return lasiusFetch<testExistingConfigResponse>(getTestExistingConfigUrl(orgId, configId), {
    ...options,
    method: 'POST',
  })
}

export type listProjectsResponse200 = {
  data: ModelsListProjectsResponse
  status: 200
}

export type listProjectsResponse400 = {
  data: ListProjects400
  status: 400
}

export type listProjectsResponse403 = {
  data: void
  status: 403
}

export type listProjectsResponse404 = {
  data: void
  status: 404
}

export type listProjectsResponseSuccess = listProjectsResponse200 & {
  headers: Headers
}
export type listProjectsResponseError = (
  listProjectsResponse400 | listProjectsResponse403 | listProjectsResponse404
) & {
  headers: Headers
}

export type listProjectsResponse = listProjectsResponseSuccess | listProjectsResponseError

export const getListProjectsUrl = (orgId: string, configId: ModelsIssueImporterConfigId) => {
  return `/organisations/${orgId}/issue-importers/${configId}/projects`
}

/**
 * Fetches list of accessible projects from the configured external service (GitLab/Jira/Plane/GitHub). Returns flat list of projects with id and name for all importer types. The labels and states of one project come from getExternalProjectMetadata. Requires only OrganisationMember role since it only reads from external API.
 * @summary List available projects from external service
 */
export const listProjects = async (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<listProjectsResponse> => {
  return lasiusFetch<listProjectsResponse>(getListProjectsUrl(orgId, configId), {
    ...options,
    method: 'GET',
  })
}

export type addProjectMappingResponse200 = {
  data: ModelsIssueImporterConfigResponse
  status: 200
}

export type addProjectMappingResponse400 = {
  data: void
  status: 400
}

export type addProjectMappingResponse403 = {
  data: void
  status: 403
}

export type addProjectMappingResponse404 = {
  data: void
  status: 404
}

export type addProjectMappingResponseSuccess = addProjectMappingResponse200 & {
  headers: Headers
}
export type addProjectMappingResponseError = (
  addProjectMappingResponse400 | addProjectMappingResponse403 | addProjectMappingResponse404
) & {
  headers: Headers
}

export type addProjectMappingResponse =
  addProjectMappingResponseSuccess | addProjectMappingResponseError

export const getAddProjectMappingUrl = (orgId: string, configId: ModelsIssueImporterConfigId) => {
  return `/organisations/${orgId}/issue-importers/${configId}/projects`
}

/**
 * @summary Add project mapping to configuration (Organisation Admin only)
 */
export const addProjectMapping = async (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  modelsCreateProjectMapping: ModelsCreateProjectMapping,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<addProjectMappingResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {}
    if (h instanceof Headers) return Object.fromEntries(h.entries())
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      )
    }
    const headers: Record<string, string | readonly string[]> = {}
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value
    }
    return headers
  }
  return lasiusFetch<addProjectMappingResponse>(getAddProjectMappingUrl(orgId, configId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(modelsCreateProjectMapping),
  })
}

export type getExternalProjectMetadataResponse200 = {
  data: ModelsExternalProjectMetadata
  status: 200
}

export type getExternalProjectMetadataResponse400 = {
  data: GetExternalProjectMetadata400
  status: 400
}

export type getExternalProjectMetadataResponse403 = {
  data: void
  status: 403
}

export type getExternalProjectMetadataResponse404 = {
  data: void
  status: 404
}

export type getExternalProjectMetadataResponseSuccess = getExternalProjectMetadataResponse200 & {
  headers: Headers
}
export type getExternalProjectMetadataResponseError = (
  | getExternalProjectMetadataResponse400
  | getExternalProjectMetadataResponse403
  | getExternalProjectMetadataResponse404
) & {
  headers: Headers
}

export type getExternalProjectMetadataResponse =
  getExternalProjectMetadataResponseSuccess | getExternalProjectMetadataResponseError

export const getGetExternalProjectMetadataUrl = (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  params: GetExternalProjectMetadataParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/organisations/${orgId}/issue-importers/${configId}/project-metadata?${stringifiedParams}`
    : `/organisations/${orgId}/issue-importers/${configId}/project-metadata`
}

/**
 * Fetches the labels and states that the tag filter of a project mapping offers for one external project. GitLab states are "opened", "closed", "all". GitHub states are "open", "closed", "all". Plane states are custom per project. Jira returns empty lists. The external project id is a query parameter, because a GitHub id such as owner/repo contains a slash. Requires only OrganisationMember role since it only reads from external API.
 * @summary Get the labels and states of one external project
 */
export const getExternalProjectMetadata = async (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  params: GetExternalProjectMetadataParams,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<getExternalProjectMetadataResponse> => {
  return lasiusFetch<getExternalProjectMetadataResponse>(
    getGetExternalProjectMetadataUrl(orgId, configId, params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export type listGithubResourceOwnersResponse200 = {
  data: ModelsListProjectsResponse
  status: 200
}

export type listGithubResourceOwnersResponse400 = {
  data: ListGithubResourceOwners400
  status: 400
}

export type listGithubResourceOwnersResponseSuccess = listGithubResourceOwnersResponse200 & {
  headers: Headers
}
export type listGithubResourceOwnersResponseError = listGithubResourceOwnersResponse400 & {
  headers: Headers
}

export type listGithubResourceOwnersResponse =
  listGithubResourceOwnersResponseSuccess | listGithubResourceOwnersResponseError

export const getListGithubResourceOwnersUrl = (orgId: string) => {
  return `/organisations/${orgId}/issue-importers/github/resource-owners`
}

/**
 * Lists available resource owners for a GitHub token. Returns the authenticated user plus all organizations they have access to. This helps users select the correct resource owner when creating organization-scoped fine-grained tokens. GitHub-specific endpoint.
 * @summary List GitHub resource owners (user + organizations)
 */
export const listGithubResourceOwners = async (
  orgId: string,
  modelsCreateIssueImporterConfig: ModelsCreateIssueImporterConfig,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<listGithubResourceOwnersResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {}
    if (h instanceof Headers) return Object.fromEntries(h.entries())
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      )
    }
    const headers: Record<string, string | readonly string[]> = {}
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value
    }
    return headers
  }
  return lasiusFetch<listGithubResourceOwnersResponse>(getListGithubResourceOwnersUrl(orgId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(modelsCreateIssueImporterConfig),
  })
}

export type refreshTagsResponse202 = {
  data: RefreshTags202
  status: 202
}

export type refreshTagsResponse403 = {
  data: void
  status: 403
}

export type refreshTagsResponse404 = {
  data: RefreshTags404
  status: 404
}

export type refreshTagsResponseSuccess = refreshTagsResponse202 & {
  headers: Headers
}
export type refreshTagsResponseError = (refreshTagsResponse403 | refreshTagsResponse404) & {
  headers: Headers
}

export type refreshTagsResponse = refreshTagsResponseSuccess | refreshTagsResponseError

export const getRefreshTagsUrl = (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  mappingId: ModelsProjectMappingId,
) => {
  return `/organisations/${orgId}/issue-importers/${configId}/projects/${mappingId}/refresh-tags`
}

/**
 * Triggers an immediate tag refresh for a specific project mapping. Sends a message to the worker to fetch tags from the external service (GitLab/Jira/Plane/GitHub) right away, bypassing the scheduled check interval. Tags will be updated within seconds. Requires only OrganisationMember role as this is a read-like operation.
 * @summary Force immediate tag refresh for a project
 */
export const refreshTags = async (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  mappingId: ModelsProjectMappingId,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<refreshTagsResponse> => {
  return lasiusFetch<refreshTagsResponse>(getRefreshTagsUrl(orgId, configId, mappingId), {
    ...options,
    method: 'POST',
  })
}

export type updateProjectMappingResponse200 = {
  data: ModelsIssueImporterConfigResponse
  status: 200
}

export type updateProjectMappingResponse400 = {
  data: void
  status: 400
}

export type updateProjectMappingResponse403 = {
  data: void
  status: 403
}

export type updateProjectMappingResponse404 = {
  data: void
  status: 404
}

export type updateProjectMappingResponseSuccess = updateProjectMappingResponse200 & {
  headers: Headers
}
export type updateProjectMappingResponseError = (
  | updateProjectMappingResponse400
  | updateProjectMappingResponse403
  | updateProjectMappingResponse404
) & {
  headers: Headers
}

export type updateProjectMappingResponse =
  updateProjectMappingResponseSuccess | updateProjectMappingResponseError

export const getUpdateProjectMappingUrl = (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  mappingId: ModelsProjectMappingId,
) => {
  return `/organisations/${orgId}/issue-importers/${configId}/projects/${mappingId}`
}

/**
 * @summary Update project mapping in configuration (Organisation Admin only)
 */
export const updateProjectMapping = async (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  mappingId: ModelsProjectMappingId,
  modelsUpdateProjectMapping: ModelsUpdateProjectMapping,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<updateProjectMappingResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {}
    if (h instanceof Headers) return Object.fromEntries(h.entries())
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      )
    }
    const headers: Record<string, string | readonly string[]> = {}
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value
    }
    return headers
  }
  return lasiusFetch<updateProjectMappingResponse>(
    getUpdateProjectMappingUrl(orgId, configId, mappingId),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
      body: JSON.stringify(modelsUpdateProjectMapping),
    },
  )
}

export type removeProjectMappingResponse200 = {
  data: ModelsIssueImporterConfigResponse
  status: 200
}

export type removeProjectMappingResponse403 = {
  data: void
  status: 403
}

export type removeProjectMappingResponse404 = {
  data: void
  status: 404
}

export type removeProjectMappingResponseSuccess = removeProjectMappingResponse200 & {
  headers: Headers
}
export type removeProjectMappingResponseError = (
  removeProjectMappingResponse403 | removeProjectMappingResponse404
) & {
  headers: Headers
}

export type removeProjectMappingResponse =
  removeProjectMappingResponseSuccess | removeProjectMappingResponseError

export const getRemoveProjectMappingUrl = (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  mappingId: ModelsProjectMappingId,
) => {
  return `/organisations/${orgId}/issue-importers/${configId}/projects/${mappingId}`
}

/**
 * @summary Remove project mapping from configuration (Organisation Admin only)
 */
export const removeProjectMapping = async (
  orgId: string,
  configId: ModelsIssueImporterConfigId,
  mappingId: ModelsProjectMappingId,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<removeProjectMappingResponse> => {
  return lasiusFetch<removeProjectMappingResponse>(
    getRemoveProjectMappingUrl(orgId, configId, mappingId),
    {
      ...options,
      method: 'DELETE',
    },
  )
}
