import { useApiProxy } from '~/hooks/use-api-proxy'

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import {
	type ModelsAcceptInvitationRequest,
	type ModelsInvitation,
} from '../../lasius'
export function useAcceptInvitation() {
	return useApiProxy<
		ModelsInvitation,
		ModelsAcceptInvitationRequest,
		{ invitationId: string }
	>({
		getUrl: ({ invitationId }) => `/invitations/${invitationId}/accept`,
		method: 'POST',
	})
}
export function useDeclineInvitation() {
	return useApiProxy<ModelsInvitation, undefined, { invitationId: string }>({
		getUrl: ({ invitationId }) => `/invitations/${invitationId}/decline`,
		method: 'POST',
	})
} /**
 * @summary get detail of an invitation
 */
export function useGetInvitation() {
	return useApiProxy<ModelsInvitation, undefined, { invitationId: string }>({
		getUrl: ({ invitationId }) => `/invitations/${invitationId}`,
		method: 'GET',
	})
}
