import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import {
  type ModelsAcceptInvitationRequest,
  type ModelsInvitation,
} from '../../lasius'
export function useAcceptInvitation(
  options?: ApiProxyOptions<ModelsInvitation>,
) {
  return useApiProxy<
    ModelsInvitation,
    ModelsAcceptInvitationRequest,
    { invitationId: string }
  >(
    {
      getUrl: ({ invitationId }) => `/invitations/${invitationId}/accept`,
      method: 'POST',
    },
    options,
  )
}
export function useDeclineInvitation(
  options?: ApiProxyOptions<ModelsInvitation>,
) {
  return useApiProxy<ModelsInvitation, undefined, { invitationId: string }>(
    {
      getUrl: ({ invitationId }) => `/invitations/${invitationId}/decline`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary get detail of an invitation
 */
export function useGetInvitation(options?: ApiProxyOptions<ModelsInvitation>) {
  return useApiProxy<ModelsInvitation, undefined, { invitationId: string }>(
    {
      getUrl: ({ invitationId }) => `/invitations/${invitationId}`,
      method: 'GET',
    },
    options,
  )
}
