/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type {
  GetAggregatedStatisticsByProjectParams,
  GetProjectBookingListParams,
  ModelsBooking,
  ModelsBookingStats,
} from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
/**
 * @summary Get statistics about bookings for the selected project within the selected timeframe
 */
function getGetProjectBookingListUrl(
  orgId: string,
  projectId: string,
  params?: GetProjectBookingListParams,
) {
  const normalizedParams = new URLSearchParams()
  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })
  const query = normalizedParams.toString()
  return query
    ? `/organisations/${orgId}/projects/${projectId}/bookings/history` + '?' + query
    : `/organisations/${orgId}/projects/${projectId}/bookings/history`
}

export function useGetProjectBookingList(options?: ApiProxyOptions<ModelsBooking[]>) {
  return useApiProxy<
    ModelsBooking[],
    undefined,
    { orgId: string; projectId: string; params?: GetProjectBookingListParams }
  >(
    {
      getUrl: ({ orgId, projectId, params }) =>
        getGetProjectBookingListUrl(orgId, projectId, params),
      method: 'GET',
    },
    options,
  )
}
function getGetAggregatedStatisticsByProjectUrl(
  orgId: string,
  projectId: string,
  params?: GetAggregatedStatisticsByProjectParams,
) {
  const normalizedParams = new URLSearchParams()
  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })
  const query = normalizedParams.toString()
  return query
    ? `/organisations/${orgId}/projects/${projectId}/bookings/stats/aggregated` + '?' + query
    : `/organisations/${orgId}/projects/${projectId}/bookings/stats/aggregated`
}

export function useGetAggregatedStatisticsByProject(
  options?: ApiProxyOptions<ModelsBookingStats[]>,
) {
  return useApiProxy<
    ModelsBookingStats[],
    undefined,
    { orgId: string; projectId: string; params?: GetAggregatedStatisticsByProjectParams }
  >(
    {
      getUrl: ({ orgId, projectId, params }) =>
        getGetAggregatedStatisticsByProjectUrl(orgId, projectId, params),
      method: 'GET',
    },
    options,
  )
}
