/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsTag, ModelsUpdateUserOrganisation, ModelsUser } from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
/**
 * @summary Change current user's working hours for the selected organisation
 */
export function useUpdateWorkingHoursByOrganisation(options?: ApiProxyOptions<ModelsUser>) {
  return useApiProxy<ModelsUser, ModelsUpdateUserOrganisation, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/user-organisations/organisations/${orgId}/working-hours`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary Remove current user's membership from selected organisation
 */
export function useDeleteUserMembershipByOrganisation(options?: ApiProxyOptions<void>) {
  return useApiProxy<void, undefined, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/user-organisations/organisations/${orgId}/leave`,
      method: 'DELETE',
    },
    options,
  )
} /**
 * @summary Get tags by organisation and project
 */
export function useGetTagsByProject(options?: ApiProxyOptions<ModelsTag[]>) {
  return useApiProxy<ModelsTag[], undefined, { orgId: string; projectId: string }>(
    {
      getUrl: ({ orgId, projectId }) =>
        `/user-organisations/organisations/${orgId}/projects/${projectId}/tags`,
      method: 'GET',
    },
    options,
  )
}
