/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type GetExternalProjectMetadata400Error =
  (typeof GetExternalProjectMetadata400Error)[keyof typeof GetExternalProjectMetadata400Error]

export const GetExternalProjectMetadata400Error = {
  project_metadata_failed: 'project_metadata_failed',
} as const
