/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type GetExternalProjectMetadata400Status =
  (typeof GetExternalProjectMetadata400Status)[keyof typeof GetExternalProjectMetadata400Status]

export const GetExternalProjectMetadata400Status = {
  error: 'error',
} as const
