/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { GetExternalProjectMetadata400Error } from './getExternalProjectMetadata400Error.ts'
import type { GetExternalProjectMetadata400Status } from './getExternalProjectMetadata400Status.ts'

export type GetExternalProjectMetadata400 = {
  status?: GetExternalProjectMetadata400Status
  message?: string
  error?: GetExternalProjectMetadata400Error
}
