/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type GetOrganisationBookingAggregatedStatsGranularity =
  (typeof GetOrganisationBookingAggregatedStatsGranularity)[keyof typeof GetOrganisationBookingAggregatedStatsGranularity]

export const GetOrganisationBookingAggregatedStatsGranularity = {
  All: 'All',
  Year: 'Year',
  Month: 'Month',
  Week: 'Week',
  Day: 'Day',
} as const
