/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { GetOrganisationBookingAggregatedStatsGranularity } from './getOrganisationBookingAggregatedStatsGranularity.ts'

export type GetOrganisationBookingAggregatedStatsParams = {
  source: string
  /**
   * @pattern yyyy-MM-dd
   */
  from: string
  /**
   * @pattern yyyy-MM-dd
   */
  to: string
  granularity: GetOrganisationBookingAggregatedStatsGranularity
}
