/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type GetOrganisationBookingListParams = {
  /**
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSS
   */
  from: string
  /**
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSS
   */
  to: string
  /**
   * @nullable
   */
  limit?: number | null
  /**
   * @nullable
   */
  skip?: number | null
}
