/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type GetUserBookingAggregatedStatsByOrganisationGranularity =
  (typeof GetUserBookingAggregatedStatsByOrganisationGranularity)[keyof typeof GetUserBookingAggregatedStatsByOrganisationGranularity]

export const GetUserBookingAggregatedStatsByOrganisationGranularity = {
  All: 'All',
  Year: 'Year',
  Month: 'Month',
  Week: 'Week',
  Day: 'Day',
} as const
