/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type ListProjects400Error = (typeof ListProjects400Error)[keyof typeof ListProjects400Error]

export const ListProjects400Error = {
  list_projects_failed: 'list_projects_failed',
} as const
