/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ListGithubResourceOwners400Error } from './listGithubResourceOwners400Error.ts'
import type { ListGithubResourceOwners400Status } from './listGithubResourceOwners400Status.ts'

export type ListGithubResourceOwners400 = {
  status?: ListGithubResourceOwners400Status
  message?: string
  error?: ListGithubResourceOwners400Error
}
