/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ListProjects400Error } from './listProjects400Error.ts'
import type { ListProjects400Status } from './listProjects400Status.ts'

export type ListProjects400 = {
  status?: ListProjects400Status
  message?: string
  error?: ListProjects400Error
}
