/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type ListProjects400Status =
  (typeof ListProjects400Status)[keyof typeof ListProjects400Status]

export const ListProjects400Status = {
  error: 'error',
} as const
