/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsCreateIssueImporterConfigResourceOwnerType } from './modelsCreateIssueImporterConfigResourceOwnerType.ts'
import type { ModelsImporterType } from './modelsImporterType.ts'

export interface ModelsCreateIssueImporterConfig {
  importerType: ModelsImporterType
  name: string
  baseUrl: string
  checkFrequency: number
  /** @nullable */
  accessToken?: string | null
  /** @nullable */
  consumerKey?: string | null
  /** @nullable */
  privateKey?: string | null
  /** @nullable */
  apiKey?: string | null
  /** @nullable */
  workspace?: string | null
  /**
   * GitHub resource owner (organization or user login) for the token
   * @nullable
   */
  resourceOwner?: string | null
  /**
   * Type of the resource owner (User or Organization)
   * @nullable
   */
  resourceOwnerType?: ModelsCreateIssueImporterConfigResourceOwnerType
}
