/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type ModelsUserStubRole = (typeof ModelsUserStubRole)[keyof typeof ModelsUserStubRole]

export const ModelsUserStubRole = {
  FreeUser: 'FreeUser',
  Administrator: 'Administrator',
} as const
