/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type ModelsSimpleTagType = (typeof ModelsSimpleTagType)[keyof typeof ModelsSimpleTagType]

export const ModelsSimpleTagType = {
  SimpleTag: 'SimpleTag',
} as const
