/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsGithubIssueTagType } from './modelsGithubIssueTagType.ts'
import type { ModelsSimpleTag } from './modelsSimpleTag.ts'

export interface ModelsGithubIssueTag {
  id: string
  repoOwner: string
  repoName: string
  issueNumber: number
  /** @nullable */
  summary?: string | null
  relatedTags: ModelsSimpleTag[]
  issueLink: string
  type: ModelsGithubIssueTagType
}
