/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsUserStubRole } from './modelsUserStubRole.ts'

export interface ModelsUserStub {
  id: string
  key: string
  email: string
  firstName: string
  lastName: string
  active: boolean
  role: ModelsUserStubRole
}
