/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type ModelsJoinOrganisationInvitationRole =
  (typeof ModelsJoinOrganisationInvitationRole)[keyof typeof ModelsJoinOrganisationInvitationRole]

export const ModelsJoinOrganisationInvitationRole = {
  OrganisationMember: 'OrganisationMember',
  OrganisationAdministrator: 'OrganisationAdministrator',
} as const
