/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type ModelsPlaneConfigResponseImporterType =
  (typeof ModelsPlaneConfigResponseImporterType)[keyof typeof ModelsPlaneConfigResponseImporterType]

export const ModelsPlaneConfigResponseImporterType = {
  plane: 'plane',
} as const
