/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsBookingStatsByCategory } from './modelsBookingStatsByCategory.ts'
import type { ModelsBookingStatsCategory } from './modelsBookingStatsCategory.ts'

export interface ModelsBookingStats {
  category: ModelsBookingStatsCategory
  values: ModelsBookingStatsByCategory[]
}
