/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsGithubTagConfiguration } from './modelsGithubTagConfiguration.ts'

export interface ModelsGithubProjectSettings {
  githubRepoOwner: string
  githubRepoName: string
  /** @nullable */
  externalProjectName?: string | null
  /** @nullable */
  maxResults?: number | null
  /** @nullable */
  params?: string | null
  /** @nullable */
  projectKeyPrefix?: string | null
  tagConfiguration: ModelsGithubTagConfiguration
}
