/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsEntityReference } from './modelsEntityReference.ts'
import type { ModelsEntityReferenceModelsUserId } from './modelsEntityReferenceModelsUserId.ts'

export interface ModelsOrganisation {
  id: string
  key: string
  private: boolean
  active: boolean
  createdBy: ModelsEntityReference
  deactivatedBy?: ModelsEntityReferenceModelsUserId | null
}
