/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsConnectivityIssue } from './modelsConnectivityIssue.ts'
import type { ModelsConnectivityStatus } from './modelsConnectivityStatus.ts'
import type { ModelsProjectSyncStats } from './modelsProjectSyncStats.ts'

/**
 * Overall health and sync statistics for an issue importer configuration
 */
export interface ModelsConfigSyncStatus {
  connectivityStatus: ModelsConnectivityStatus
  /**
   * Last time connectivity was verified
   * @nullable
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
   */
  lastConnectivityCheck?: string | null
  currentIssue?: ModelsConnectivityIssue | null
  /** Per-project sync statistics */
  projectStats: ModelsProjectSyncStats[]
  /** Number of projects mapped to this config */
  totalProjectsMapped: number
  /** Total issues synced across all projects */
  totalIssuesSynced: number
  /**
   * Last successful sync across any project
   * @nullable
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
   */
  lastSuccessfulSync?: string | null
  /**
   * When next sync is scheduled
   * @nullable
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
   */
  nextScheduledSync?: string | null
}
