/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsJiraProjectMapping } from './modelsJiraProjectMapping.ts'

export interface ModelsUpdateJiraConfig {
  name?: string
  baseUrl?: string
  consumerKey?: string
  privateKey?: string
  accessToken?: string
  checkFrequency?: number
  projects?: ModelsJiraProjectMapping[]
}
