/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsAuditInfoResponse } from './modelsAuditInfoResponse.ts'
import type { ModelsConfigSyncStatus } from './modelsConfigSyncStatus.ts'
import type { ModelsIssueImporterConfigId } from './modelsIssueImporterConfigId.ts'
import type { ModelsPlaneConfigResponseImporterType } from './modelsPlaneConfigResponseImporterType.ts'
import type { ModelsPlaneProjectMapping } from './modelsPlaneProjectMapping.ts'

export interface ModelsPlaneConfigResponse {
  id: ModelsIssueImporterConfigId
  importerType: ModelsPlaneConfigResponseImporterType
  name: string
  baseUrl: string
  checkFrequency: number
  projects: ModelsPlaneProjectMapping[]
  syncStatus: ModelsConfigSyncStatus
  audit: ModelsAuditInfoResponse
  workspace?: string
  type?: string
  projectCount: number
}
