/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

/**
 * Type of the resource owner (User or Organization)
 * @nullable
 */
export type ModelsCreateIssueImporterConfigResourceOwnerType =
  | (typeof ModelsCreateIssueImporterConfigResourceOwnerType)[keyof typeof ModelsCreateIssueImporterConfigResourceOwnerType]
  | null

export const ModelsCreateIssueImporterConfigResourceOwnerType = {
  User: 'User',
  Organization: 'Organization',
} as const
