/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsUserStub } from './modelsUserStub.ts'

/**
 * Audit information with full user details for API responses
 */
export interface ModelsAuditInfoResponse {
  createdBy: ModelsUserStub
  /**
   * Timestamp when entity was created
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
   */
  createdAt: string
  updatedBy: ModelsUserStub
  /**
   * Timestamp when entity was last updated
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
   */
  updatedAt: string
}
