/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsJiraIssueTagType } from './modelsJiraIssueTagType.ts'

export interface ModelsJiraIssueTag {
  id: string
  baseUrl: string
  /** @nullable */
  summary?: string | null
  url: string
  projectKey: string
  type: ModelsJiraIssueTagType
}
