/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { ModelsAuditInfoResponse } from './modelsAuditInfoResponse'
import type { ModelsConfigSyncStatus } from './modelsConfigSyncStatus'
import type { ModelsGitlabConfigResponseImporterType } from './modelsGitlabConfigResponseImporterType'
import type { ModelsGitlabProjectMapping } from './modelsGitlabProjectMapping'
import type { ModelsIssueImporterConfigId } from './modelsIssueImporterConfigId'

export interface ModelsGitlabConfigResponse {
  id: ModelsIssueImporterConfigId
  importerType: ModelsGitlabConfigResponseImporterType
  name: string
  baseUrl: string
  checkFrequency: number
  projects: ModelsGitlabProjectMapping[]
  syncStatus: ModelsConfigSyncStatus
  audit: ModelsAuditInfoResponse
  type?: string
  projectCount: number
}
