/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export interface ModelsStopBookingRequest {
  /**
   * @nullable
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
   */
  end?: string | null
}
