/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsConnectivityIssue } from './modelsConnectivityIssue.ts'

/**
 * Sync statistics for a specific project mapping
 */
export interface ModelsProjectSyncStats {
  /** Project ID */
  projectId: string
  /** Project name */
  projectName: string
  /**
   * Last successful sync timestamp
   * @nullable
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
   */
  lastSyncAt?: string | null
  /** Number of issues synced in last run */
  lastSyncIssueCount: number
  /** Total issues synced since mapping creation */
  totalIssuesSynced: number
  /** Number of consecutive sync failures (circuit breaker) */
  consecutiveFailures: number
  lastError?: ModelsConnectivityIssue | null
}
