/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export interface ModelsGithubTagConfiguration {
  useLabels: boolean
  labelFilter: string[]
  useMilestone: boolean
  useTitle: boolean
  useAssignees: boolean
  includeOnlyIssuesWithLabels: string[]
  includeOnlyIssuesWithState: string[]
}
