/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type ModelsJiraIssueTagType =
  (typeof ModelsJiraIssueTagType)[keyof typeof ModelsJiraIssueTagType]

export const ModelsJiraIssueTagType = {
  JiraIssueTag: 'JiraIssueTag',
} as const
