/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type ModelsImporterType = (typeof ModelsImporterType)[keyof typeof ModelsImporterType]

export const ModelsImporterType = {
  gitlab: 'gitlab',
  jira: 'jira',
  plane: 'plane',
  github: 'github',
} as const
