/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsTag } from './modelsTag.ts'

export interface ModelsStartBookingRequest {
  projectId: string
  tags: ModelsTag[]
  /**
   * @nullable
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
   */
  start?: string | null
}
