/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

/**
 * Type of the resource owner (GitHub only, User or Organization)
 * @nullable
 */
export type ModelsExternalProjectOwnerType =
  (typeof ModelsExternalProjectOwnerType)[keyof typeof ModelsExternalProjectOwnerType] | null

export const ModelsExternalProjectOwnerType = {
  User: 'User',
  Organization: 'Organization',
} as const
