/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsAcceptedTOS } from './modelsAcceptedTOS.ts'
import type { ModelsUserOrganisation } from './modelsUserOrganisation.ts'
import type { ModelsUserRole } from './modelsUserRole.ts'
import type { ModelsUserSettings } from './modelsUserSettings.ts'

export interface ModelsUser {
  id: string
  key: string
  email: string
  firstName: string
  lastName: string
  active: boolean
  role: ModelsUserRole
  organisations: ModelsUserOrganisation[]
  settings: ModelsUserSettings
  acceptedTOS?: ModelsAcceptedTOS | null
}
