/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsAuditInfoResponse } from './modelsAuditInfoResponse.ts'
import type { ModelsConfigSyncStatus } from './modelsConfigSyncStatus.ts'
import type { ModelsExternalProject } from './modelsExternalProject.ts'
import type { ModelsGithubConfigResponseImporterType } from './modelsGithubConfigResponseImporterType.ts'
import type { ModelsGithubConfigResponseResourceOwnerType } from './modelsGithubConfigResponseResourceOwnerType.ts'
import type { ModelsGithubProjectMapping } from './modelsGithubProjectMapping.ts'
import type { ModelsIssueImporterConfigId } from './modelsIssueImporterConfigId.ts'

export interface ModelsGithubConfigResponse {
  id: ModelsIssueImporterConfigId
  importerType: ModelsGithubConfigResponseImporterType
  name: string
  baseUrl: string
  checkFrequency: number
  projects: ModelsGithubProjectMapping[]
  syncStatus: ModelsConfigSyncStatus
  audit: ModelsAuditInfoResponse
  /**
   * GitHub resource owner (organization or user login) for the token
   * @nullable
   */
  resourceOwner?: string | null
  /**
   * Type of the resource owner (User or Organization)
   * @nullable
   */
  resourceOwnerType?: ModelsGithubConfigResponseResourceOwnerType
  /**
   * List of available resource owners (user + organizations) for the token
   * @nullable
   */
  availableResourceOwners?: ModelsExternalProject[] | null
  type?: string
  projectCount: number
}
