/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsEntityReference } from './modelsEntityReference.ts'
import type { ModelsInvitationOutcome } from './modelsInvitationOutcome.ts'
import type { ModelsJoinProjectInvitationRole } from './modelsJoinProjectInvitationRole.ts'
import type { ModelsJoinProjectInvitationType } from './modelsJoinProjectInvitationType.ts'

export interface ModelsJoinProjectInvitation {
  id: string
  invitedEmail: string
  /** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
  createDate: string
  createdBy: ModelsEntityReference
  /** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
  expiration: string
  sharedByOrganisationReference: ModelsEntityReference
  projectReference: ModelsEntityReference
  role: ModelsJoinProjectInvitationRole
  outcome?: ModelsInvitationOutcome | null
  type: ModelsJoinProjectInvitationType
}
