/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { ModelsGithubConfigResponse } from './modelsGithubConfigResponse'
import type { ModelsGitlabConfigResponse } from './modelsGitlabConfigResponse'
import type { ModelsJiraConfigResponse } from './modelsJiraConfigResponse'
import type { ModelsPlaneConfigResponse } from './modelsPlaneConfigResponse'

export type ModelsIssueImporterConfigResponse =
  | (ModelsGitlabConfigResponse & unknown)
  | (ModelsJiraConfigResponse & unknown)
  | (ModelsPlaneConfigResponse & unknown)
  | (ModelsGithubConfigResponse & unknown)
