/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type ModelsGithubIssueTagType =
  (typeof ModelsGithubIssueTagType)[keyof typeof ModelsGithubIssueTagType]

export const ModelsGithubIssueTagType = {
  GithubIssueTag: 'GithubIssueTag',
} as const
