/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsEntityReference } from './modelsEntityReference.ts'
import type { ModelsInvitationOutcomeStatus } from './modelsInvitationOutcomeStatus.ts'

export interface ModelsInvitationOutcome {
  userReference: ModelsEntityReference
  /** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
  dateTime: string
  status: ModelsInvitationOutcomeStatus
}
