/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsEntityReference } from './modelsEntityReference.ts'
import type { ModelsLocalDateTimeWithTimeZone } from './modelsLocalDateTimeWithTimeZone.ts'
import type { ModelsTag } from './modelsTag.ts'

export interface ModelsBooking {
  id: string
  start: ModelsLocalDateTimeWithTimeZone
  end?: ModelsLocalDateTimeWithTimeZone | null
  userReference: ModelsEntityReference
  organisationReference: ModelsEntityReference
  projectReference: ModelsEntityReference
  tags: ModelsTag[]
  bookingHash: number
}
