/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsWorkingHours } from './modelsWorkingHours.ts'

export interface ModelsCreateOrganisation {
  key: string
  plannedWorkingHours?: ModelsWorkingHours | null
}
