/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsInvitation } from './modelsInvitation.ts'
import type { ModelsInvitationStatusResponseStatus } from './modelsInvitationStatusResponseStatus.ts'

export interface ModelsInvitationStatusResponse {
  status: ModelsInvitationStatusResponseStatus
  invitation: ModelsInvitation
}
