/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsGitlabProjectSettings } from './modelsGitlabProjectSettings.ts'
import type { ModelsProjectMappingId } from './modelsProjectMappingId.ts'

export interface ModelsGitlabProjectMapping {
  id: ModelsProjectMappingId
  projectId: string
  settings: ModelsGitlabProjectSettings
}
