/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

/**
 * Tracks who created and last modified an entity
 */
export interface ModelsAuditInfo {
  /** User ID of entity creator */
  createdBy: string
  /** Timestamp when entity was created */
  createdAt: string
  /** User ID of last updater */
  updatedBy: string
  /** Timestamp when entity was last updated */
  updatedAt: string
}
