/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsGithubIssueTag } from './modelsGithubIssueTag.ts'
import type { ModelsGitlabIssueTag } from './modelsGitlabIssueTag.ts'
import type { ModelsJiraIssueTag } from './modelsJiraIssueTag.ts'
import type { ModelsPlaneIssueTag } from './modelsPlaneIssueTag.ts'
import type { ModelsSimpleTag } from './modelsSimpleTag.ts'
import type { ModelsTagGroup } from './modelsTagGroup.ts'

export type ModelsTag =
  | (ModelsSimpleTag & unknown)
  | (ModelsTagGroup & unknown)
  | (ModelsGitlabIssueTag & unknown)
  | (ModelsJiraIssueTag & unknown)
  | (ModelsPlaneIssueTag & unknown)
  | (ModelsGithubIssueTag & unknown)
