/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsJiraProjectSettings } from './modelsJiraProjectSettings.ts'
import type { ModelsProjectMappingId } from './modelsProjectMappingId.ts'

export interface ModelsJiraProjectMapping {
  id: ModelsProjectMappingId
  projectId: string
  settings: ModelsJiraProjectSettings
}
