/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsExternalProject } from './modelsExternalProject.ts'
import type { ModelsExternalWorkspace } from './modelsExternalWorkspace.ts'

export interface ModelsListProjectsResponse {
  /** @nullable */
  projects?: ModelsExternalProject[] | null
  /** @nullable */
  workspaces?: ModelsExternalWorkspace[] | null
}
