/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsGitlabProjectMapping } from './modelsGitlabProjectMapping.ts'

export interface ModelsUpdateGitlabConfig {
  name?: string
  baseUrl?: string
  accessToken?: string
  checkFrequency?: number
  projects?: ModelsGitlabProjectMapping[]
}
