/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsPlaneProjectSettings } from './modelsPlaneProjectSettings.ts'
import type { ModelsProjectMappingId } from './modelsProjectMappingId.ts'

export interface ModelsPlaneProjectMapping {
  id: ModelsProjectMappingId
  projectId: string
  settings: ModelsPlaneProjectSettings
}
