/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsUserToOrganisationAssignmentRole } from './modelsUserToOrganisationAssignmentRole.ts'

export interface ModelsUserToOrganisationAssignment {
  email: string
  role: ModelsUserToOrganisationAssignmentRole
}
