/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsAuditInfoResponse } from './modelsAuditInfoResponse.ts'
import type { ModelsConfigSyncStatus } from './modelsConfigSyncStatus.ts'
import type { ModelsIssueImporterConfigId } from './modelsIssueImporterConfigId.ts'
import type { ModelsJiraConfigResponseImporterType } from './modelsJiraConfigResponseImporterType.ts'
import type { ModelsJiraProjectMapping } from './modelsJiraProjectMapping.ts'

export interface ModelsJiraConfigResponse {
  id: ModelsIssueImporterConfigId
  importerType: ModelsJiraConfigResponseImporterType
  name: string
  baseUrl: string
  checkFrequency: number
  projects: ModelsJiraProjectMapping[]
  syncStatus: ModelsConfigSyncStatus
  audit: ModelsAuditInfoResponse
  type?: string
  projectCount: number
}
