/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsEntityReference } from './modelsEntityReference.ts'
import type { ModelsUserOrganisationRole } from './modelsUserOrganisationRole.ts'
import type { ModelsUserProject } from './modelsUserProject.ts'
import type { ModelsWorkingHours } from './modelsWorkingHours.ts'

export interface ModelsUserOrganisation {
  organisationReference: ModelsEntityReference
  private: boolean
  role: ModelsUserOrganisationRole
  plannedWorkingHours: ModelsWorkingHours
  projects: ModelsUserProject[]
}
