/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsJoinOrganisationInvitation } from './modelsJoinOrganisationInvitation.ts'
import type { ModelsJoinProjectInvitation } from './modelsJoinProjectInvitation.ts'

export type ModelsInvitation =
  (ModelsJoinOrganisationInvitation & unknown) | (ModelsJoinProjectInvitation & unknown)
