/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsGithubConfigResponse } from './modelsGithubConfigResponse.ts'
import type { ModelsGitlabConfigResponse } from './modelsGitlabConfigResponse.ts'
import type { ModelsJiraConfigResponse } from './modelsJiraConfigResponse.ts'
import type { ModelsPlaneConfigResponse } from './modelsPlaneConfigResponse.ts'

export type ModelsIssueImporterConfigResponse =
  | (ModelsGitlabConfigResponse & unknown)
  | (ModelsJiraConfigResponse & unknown)
  | (ModelsPlaneConfigResponse & unknown)
  | (ModelsGithubConfigResponse & unknown)
