/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsEntityReference } from './modelsEntityReference.ts'
import type { ModelsInvitationOutcomeStatus } from './modelsInvitationOutcomeStatus.ts'

export interface ModelsInvitationOutcome {
  userReference: ModelsEntityReference
  /** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
  dateTime: string
  status: ModelsInvitationOutcomeStatus
}
