/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type ModelsUserStubRole = (typeof ModelsUserStubRole)[keyof typeof ModelsUserStubRole]

export const ModelsUserStubRole = {
  FreeUser: 'FreeUser',
  Administrator: 'Administrator',
} as const
