/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type RefreshTags202ImporterType =
  (typeof RefreshTags202ImporterType)[keyof typeof RefreshTags202ImporterType]

export const RefreshTags202ImporterType = {
  gitlab: 'gitlab',
  jira: 'jira',
  plane: 'plane',
  github: 'github',
} as const
