/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { RefreshTags202ImporterType } from './refreshTags202ImporterType.ts'
import type { RefreshTags202Status } from './refreshTags202Status.ts'

export type RefreshTags202 = {
  status?: RefreshTags202Status
  message?: string
  configId?: string
  mappingId?: string
  importerType?: RefreshTags202ImporterType
}
