/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type RefreshTags404Error = (typeof RefreshTags404Error)[keyof typeof RefreshTags404Error]

export const RefreshTags404Error = {
  config_not_found: 'config_not_found',
  mapping_not_found: 'mapping_not_found',
} as const
