/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { RefreshTags202ImporterType } from './refreshTags202ImporterType'
import type { RefreshTags202Status } from './refreshTags202Status'

export type RefreshTags202 = {
  status?: RefreshTags202Status
  message?: string
  configId?: string
  mappingId?: string
  importerType?: RefreshTags202ImporterType
}
