/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type RefreshTags404Status = (typeof RefreshTags404Status)[keyof typeof RefreshTags404Status]

export const RefreshTags404Status = {
  error: 'error',
} as const
