/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type RefreshTags404Status = (typeof RefreshTags404Status)[keyof typeof RefreshTags404Status]

export const RefreshTags404Status = {
  error: 'error',
} as const
