/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type RefreshTags202Status = (typeof RefreshTags202Status)[keyof typeof RefreshTags202Status]

export const RefreshTags202Status = {
  accepted: 'accepted',
} as const
