/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { RefreshTags202ImporterType } from './refreshTags202ImporterType.ts'
import type { RefreshTags202Status } from './refreshTags202Status.ts'

export type RefreshTags202 = {
  status?: RefreshTags202Status
  message?: string
  configId?: string
  mappingId?: string
  importerType?: RefreshTags202ImporterType
}
