/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type TestExistingConfig200Status =
  (typeof TestExistingConfig200Status)[keyof typeof TestExistingConfig200Status]

export const TestExistingConfig200Status = {
  success: 'success',
} as const
