/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { TestExistingConfig400Error } from './testExistingConfig400Error'
import type { TestExistingConfig400Status } from './testExistingConfig400Status'

export type TestExistingConfig400 = {
  status?: TestExistingConfig400Status
  message?: string
  error?: TestExistingConfig400Error
}
