/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type TestConnectivity200Status =
  (typeof TestConnectivity200Status)[keyof typeof TestConnectivity200Status]

export const TestConnectivity200Status = {
  success: 'success',
} as const
