/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { TestExistingConfig400Error } from './testExistingConfig400Error.ts'
import type { TestExistingConfig400Status } from './testExistingConfig400Status.ts'

export type TestExistingConfig400 = {
  status?: TestExistingConfig400Status
  message?: string
  error?: TestExistingConfig400Error
}
