/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type TestExistingConfig400Status =
  (typeof TestExistingConfig400Status)[keyof typeof TestExistingConfig400Status]

export const TestExistingConfig400Status = {
  error: 'error',
} as const
