/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type TestConnectivity400Error =
  (typeof TestConnectivity400Error)[keyof typeof TestConnectivity400Error]

export const TestConnectivity400Error = {
  connection_failed: 'connection_failed',
  authentication_failed: 'authentication_failed',
  unknown_host: 'unknown_host',
  timeout: 'timeout',
  connection_error: 'connection_error',
  validation_failed: 'validation_failed',
} as const
