/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { TestConnectivity400Error } from './testConnectivity400Error.ts'
import type { TestConnectivity400Status } from './testConnectivity400Status.ts'

export type TestConnectivity400 = {
  status?: TestConnectivity400Status
  message?: string
  error?: TestConnectivity400Error
}
