/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type TestConnectivity400Status =
  (typeof TestConnectivity400Status)[keyof typeof TestConnectivity400Status]

export const TestConnectivity400Status = {
  error: 'error',
} as const
