/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { TestExistingConfig200Status } from './testExistingConfig200Status.ts'

export type TestExistingConfig200 = {
  status?: TestExistingConfig200Status
  message?: string
}
