/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type TestExistingConfig200Status =
  (typeof TestExistingConfig200Status)[keyof typeof TestExistingConfig200Status]

export const TestExistingConfig200Status = {
  success: 'success',
} as const
