/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { TestConnectivity400Error } from './testConnectivity400Error.ts'
import type { TestConnectivity400Status } from './testConnectivity400Status.ts'

export type TestConnectivity400 = {
  status?: TestConnectivity400Status
  message?: string
  error?: TestConnectivity400Error
}
