/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */

export type TestExistingConfig400Error =
  (typeof TestExistingConfig400Error)[keyof typeof TestExistingConfig400Error]

export const TestExistingConfig400Error = {
  connection_failed: 'connection_failed',
  authentication_failed: 'authentication_failed',
  unknown_host: 'unknown_host',
  timeout: 'timeout',
  connection_error: 'connection_error',
} as const
