/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsBooking } from './modelsBooking.ts'
import type { WebSocketUserTimeBookingHistoryEntryAddedType } from './webSocketUserTimeBookingHistoryEntryAddedType.ts'

/**
 * New booking added to user's history
 */
export interface WebSocketUserTimeBookingHistoryEntryAdded {
  type: WebSocketUserTimeBookingHistoryEntryAddedType
  booking: ModelsBooking
}
