/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsCurrentUserTimeBooking } from './modelsCurrentUserTimeBooking.ts'
import type { WebSocketCurrentOrganisationTimeBookingsType } from './webSocketCurrentOrganisationTimeBookingsType.ts'

/**
 * Current time bookings for all users in an organization
 */
export interface WebSocketCurrentOrganisationTimeBookings {
  type: WebSocketCurrentOrganisationTimeBookingsType
  orgId: string
  timeBookings: ModelsCurrentUserTimeBooking[]
}
