/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsBookingStub } from './modelsBookingStub.ts'
import type { WebSocketFavoriteAddedType } from './webSocketFavoriteAddedType.ts'

/**
 * User added a booking to favorites
 */
export interface WebSocketFavoriteAdded {
  type: WebSocketFavoriteAddedType
  userId: string
  orgId: string
  bookingStub: ModelsBookingStub
}
