/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsConfigSyncStatus } from './modelsConfigSyncStatus.ts'
import type { ModelsImporterType } from './modelsImporterType.ts'
import type { WebSocketIssueImporterSyncStatsChangedType } from './webSocketIssueImporterSyncStatsChangedType.ts'

/**
 * Issue importer sync status changed (admin-only, negative outcomes only)
 */
export interface WebSocketIssueImporterSyncStatsChanged {
  type: WebSocketIssueImporterSyncStatsChangedType
  configId: string
  organisationId: string
  importerType: ModelsImporterType
  configName: string
  syncStatus: ModelsConfigSyncStatus
}
