/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsCurrentUserTimeBooking } from './modelsCurrentUserTimeBooking.ts'
import type { WebSocketCurrentUserTimeBookingEventType } from './webSocketCurrentUserTimeBookingEventType.ts'

/**
 * Current user's active booking update
 */
export interface WebSocketCurrentUserTimeBookingEvent {
  type: WebSocketCurrentUserTimeBookingEventType
  booking: ModelsCurrentUserTimeBooking
}
