/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type WebSocketUserTimeBookingHistoryEntryRemovedType =
  (typeof WebSocketUserTimeBookingHistoryEntryRemovedType)[keyof typeof WebSocketUserTimeBookingHistoryEntryRemovedType]

export const WebSocketUserTimeBookingHistoryEntryRemovedType = {
  UserTimeBookingHistoryEntryRemoved: 'UserTimeBookingHistoryEntryRemoved',
} as const
