/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */

export type WebSocketUserTimeBookingHistoryEntryChangedType =
  (typeof WebSocketUserTimeBookingHistoryEntryChangedType)[keyof typeof WebSocketUserTimeBookingHistoryEntryChangedType]

export const WebSocketUserTimeBookingHistoryEntryChangedType = {
  UserTimeBookingHistoryEntryChanged: 'UserTimeBookingHistoryEntryChanged',
} as const
