/**
 * Lasius - Open source time tracker for teams
 * Copyright (c) Tegonal Genossenschaft (https://tegonal.com)
 *
 * This file is part of Lasius.
 *
 * Lasius is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 *
 * Lasius is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Lasius.
 * If not, see <https://www.gnu.org/licenses/>.
 *
 */

/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.1.0-beta2+6-660a4e88+20251006-0202
 */
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsInvitationOutcome } from './modelsInvitationOutcome'
import type { ModelsJoinOrganisationInvitationRole } from './modelsJoinOrganisationInvitationRole'
import type { ModelsJoinOrganisationInvitationType } from './modelsJoinOrganisationInvitationType'

export interface ModelsJoinOrganisationInvitation {
  id: string
  invitedEmail: string
  /** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
  createDate: string
  createdBy: ModelsEntityReference
  /** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
  expiration: string
  organisationReference: ModelsEntityReference
  role: ModelsJoinOrganisationInvitationRole
  /** @nullable */
  outcome?: ModelsInvitationOutcome
  type: ModelsJoinOrganisationInvitationType
}
