import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import {
  type GetOrganisationBookingAggregatedStatsParams,
  type GetOrganisationBookingListParams,
  type ModelsBooking,
  type ModelsBookingStats,
} from '../../lasius'
export function useGetOrganisationBookingAggregatedStats(
  options?: ApiProxyOptions<ModelsBookingStats[]>,
) {
  return useApiProxy<
    ModelsBookingStats[],
    undefined,
    { orgId: string; params?: GetOrganisationBookingAggregatedStatsParams }
  >(
    {
      getUrl: ({ orgId, params }) =>
        getGetOrganisationBookingAggregatedStatsUrl(orgId, params),
      method: 'GET',
    },
    options,
  )
}

export function useGetOrganisationBookingList(
  options?: ApiProxyOptions<ModelsBooking[]>,
) {
  return useApiProxy<
    ModelsBooking[],
    undefined,
    { orgId: string; params?: GetOrganisationBookingListParams }
  >(
    {
      getUrl: ({ orgId, params }) =>
        getGetOrganisationBookingListUrl(orgId, params),
      method: 'GET',
    },
    options,
  )
} /**
 * @summary Get aggregated statistics about bookings for the selected organisation within the selected timeframe
 */
function getGetOrganisationBookingAggregatedStatsUrl(
  orgId: string,
  params?: GetOrganisationBookingAggregatedStatsParams,
) {
  const normalizedParams = new URLSearchParams()
  for (const [key, value] of Object.entries(params || {})) {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  }
  const query = normalizedParams.toString()
  return query
    ? `/organisation-bookings/organisations/${orgId}/bookings/stats/aggregated` +
        '?' +
        query
    : `/organisation-bookings/organisations/${orgId}/bookings/stats/aggregated`
}

/**
 * @summary Get bookings for the selected organisation within the selected timeframe
 */
function getGetOrganisationBookingListUrl(
  orgId: string,
  params?: GetOrganisationBookingListParams,
) {
  const normalizedParams = new URLSearchParams()
  for (const [key, value] of Object.entries(params || {})) {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  }
  const query = normalizedParams.toString()
  return query
    ? `/organisation-bookings/organisations/${orgId}/bookings/history` +
        '?' +
        query
    : `/organisation-bookings/organisations/${orgId}/bookings/history`
}
