/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsApplicationConfig, ModelsCsrfToken } from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
/**
 * @summary Get application config
 */
export function useGetConfiguration(options?: ApiProxyOptions<ModelsApplicationConfig>) {
  return useApiProxy<ModelsApplicationConfig>(
    {
      getUrl: () => `/config`,
      method: 'GET',
      skipAuth: true,
    },
    options,
  )
} /**
 * @summary Get csrf token
 */
export function useGetCsrfToken(options?: ApiProxyOptions<ModelsCsrfToken>) {
  return useApiProxy<ModelsCsrfToken>(
    {
      getUrl: () => `/csrf-token`,
      method: 'GET',
      skipAuth: true,
    },
    options,
  )
}
