import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */
import {
  type ModelsApplicationConfig,
  type ModelsCsrfToken,
} from '../../lasius'
/**
 * @summary Get application config
 */
export function useGetConfiguration(
  options?: ApiProxyOptions<ModelsApplicationConfig>,
) {
  return useApiProxy<ModelsApplicationConfig>(
    {
      getUrl: () => `/config`,
      method: 'GET',
      skipAuth: true,
    },
    options,
  )
} /**
 * @summary Get csrf token
 */
export function useGetCsrfToken(options?: ApiProxyOptions<ModelsCsrfToken>) {
  return useApiProxy<ModelsCsrfToken>(
    {
      getUrl: () => `/csrf-token`,
      method: 'GET',
      skipAuth: true,
    },
    options,
  )
}
