/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import type { ModelsInvitationStatusResponse } from './..'

import { lasiusFetch } from '../../lasius-fetch-instance'

/**
 * @summary get status of an invitation
 */
export type getInvitationStatusResponse200 = {
  data: ModelsInvitationStatusResponse
  status: 200
}

export type getInvitationStatusResponse400 = {
  data: void
  status: 400
}

export type getInvitationStatusResponseSuccess =
  getInvitationStatusResponse200 & {
    headers: Headers
  }
export type getInvitationStatusResponseError =
  getInvitationStatusResponse400 & {
    headers: Headers
  }

export type getInvitationStatusResponse =
  | getInvitationStatusResponseSuccess
  | getInvitationStatusResponseError

export const getGetInvitationStatusUrl = (invitationId: string) => {
  return `/invitations/${invitationId}/status`
}

export const getInvitationStatus = async (
  invitationId: string,
  options?: RequestInit,
): Promise<getInvitationStatusResponse> => {
  return lasiusFetch<getInvitationStatusResponse>(
    getGetInvitationStatusUrl(invitationId),
    {
      ...options,
      method: 'GET',
    },
  )
}
