/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { ModelsInvitationStatusResponse } from '.././'

import { lasiusFetch } from '../../lasius-fetch-instance'

/**
 * @summary get status of an invitation
 */
export type getInvitationStatusResponse200 = {
	data: ModelsInvitationStatusResponse
	status: 200
}

export type getInvitationStatusResponse400 = {
	data: void
	status: 400
}

export type getInvitationStatusResponseSuccess =
	getInvitationStatusResponse200 & {
		headers: Headers
	}
export type getInvitationStatusResponseError =
	getInvitationStatusResponse400 & {
		headers: Headers
	}

export type getInvitationStatusResponse =
	| getInvitationStatusResponseSuccess
	| getInvitationStatusResponseError

export const getGetInvitationStatusUrl = (invitationId: string) => {
	return `/invitations/${invitationId}/status`
}

export const getInvitationStatus = async (
	invitationId: string,
	options?: RequestInit,
): Promise<getInvitationStatusResponse> => {
	return lasiusFetch<getInvitationStatusResponse>(
		getGetInvitationStatusUrl(invitationId),
		{
			...options,
			method: 'GET',
		},
	)
}
