import { useApiProxy } from '~/hooks/use-api-proxy'

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import {
	type ModelsCreateProject,
	type ModelsInvitationResult,
	type ModelsProject,
	type ModelsUpdateProject,
	type ModelsUserStub,
	type ModelsUserToProjectAssignment,
} from '../../lasius'
export function useCreateProject() {
	return useApiProxy<ModelsProject, ModelsCreateProject, { orgId: string }>({
		getUrl: ({ orgId }) => `/organisations/${orgId}/projects`,
		method: 'POST',
	})
} /**
 * @summary Deactivate a project
 */
export function useDeactivateProject() {
	return useApiProxy<void, undefined, { orgId: string; projectId: string }>({
		getUrl: ({ orgId, projectId }) =>
			`/organisations/${orgId}/projects/${projectId}`,
		method: 'DELETE',
	})
} /**
 * Get last activity date for a project.
 */
export function useGetProjectLastActivityDate() {
	return useApiProxy<
		string | void,
		undefined,
		{ orgId: string; projectId: string }
	>({
		getUrl: ({ orgId, projectId }) =>
			`/organisations/${orgId}/projects/${projectId}/last-activity`,
		method: 'GET',
	})
}
export function useGetProjectList() {
	return useApiProxy<ModelsProject[], undefined, { orgId: string }>({
		getUrl: ({ orgId }) => `/organisations/${orgId}/projects`,
		method: 'GET',
	})
}
export function useGetProjectUserList() {
	return useApiProxy<
		ModelsUserStub[],
		undefined,
		{ orgId: string; projectId: string }
	>({
		getUrl: ({ orgId, projectId }) =>
			`/organisations/${orgId}/projects/${projectId}/users`,
		method: 'GET',
	})
}
export function useInviteProjectUser() {
	return useApiProxy<
		ModelsInvitationResult,
		ModelsUserToProjectAssignment,
		{ orgId: string; projectId: string }
	>({
		getUrl: ({ orgId, projectId }) =>
			`/organisations/${orgId}/projects/${projectId}/users`,
		method: 'POST',
	})
} /**
 * @summary Remove current user's membership from selected project and selected organisation
 */
export function useRemoveProjectOwnUser() {
	return useApiProxy<void, undefined, { orgId: string; projectId: string }>({
		getUrl: ({ orgId, projectId }) =>
			`/organisations/${orgId}/projects/${projectId}/leave`,
		method: 'DELETE',
	})
}
export function useRemoveProjectUser() {
	return useApiProxy<
		void,
		undefined,
		{ orgId: string; projectId: string; userId: string }
	>({
		getUrl: ({ orgId, projectId, userId }) =>
			`/organisations/${orgId}/projects/${projectId}/users/${userId}`,
		method: 'DELETE',
	})
} /**
 * @summary update a project
 */
export function useUpdateProject() {
	return useApiProxy<
		ModelsProject,
		ModelsUpdateProject,
		{ orgId: string; projectId: string }
	>({
		getUrl: ({ orgId, projectId }) =>
			`/organisations/${orgId}/projects/${projectId}`,
		method: 'POST',
	})
}
