import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'

/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import {
  type ModelsFavoritesRequest,
  type ModelsUserFavorites,
} from '../../lasius'
/**
 * @summary Save a new favorite booking for the current user in the selected organisation
 */
export function useAddFavoriteBooking(
  options?: ApiProxyOptions<ModelsUserFavorites[]>,
) {
  return useApiProxy<
    ModelsUserFavorites[],
    ModelsFavoritesRequest,
    { orgId: string }
  >(
    {
      getUrl: ({ orgId }) => `/user-favorites/organisations/${orgId}`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary Remove a favorite booking for the current user from the selected organisation
 */
export function useDeleteFavoriteBooking(options?: ApiProxyOptions<void>) {
  return useApiProxy<void, ModelsFavoritesRequest, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/user-favorites/organisations/${orgId}`,
      method: 'DELETE',
    },
    options,
  )
} /**
 * @summary Get current user's favorite bookings list for the selected organisation
 */
export function useGetFavoriteBookingList(
  options?: ApiProxyOptions<ModelsUserFavorites>,
) {
  return useApiProxy<ModelsUserFavorites, undefined, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/user-favorites/organisations/${orgId}`,
      method: 'GET',
    },
    options,
  )
}
