/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+345-80ac1ed7+20261007-2104
 */
import type { ModelsPersonalDataUpdate, ModelsUser } from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
/**
 * The email is read-only. A request with a changed email answers 400 with the body email_read_only.
 * @summary Change selected user's profile in selected organisation
 */
export function useUpdateUserProfileByOrganisation(options?: ApiProxyOptions<ModelsUser>) {
  return useApiProxy<ModelsUser, ModelsPersonalDataUpdate, { orgId: string; userId: string }>(
    {
      getUrl: ({ orgId, userId }) => `/users/organisations/${orgId}/users/${userId}`,
      method: 'POST',
    },
    options,
  )
}
