/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type {
  GetConfigsParams,
  GetExternalProjectMetadataParams,
  ModelsCreateIssueImporterConfig,
  ModelsCreateProjectMapping,
  ModelsExternalProjectMetadata,
  ModelsIssueImporterConfigId,
  ModelsIssueImporterConfigResponse,
  ModelsListProjectsResponse,
  ModelsProjectMappingId,
  ModelsUpdateIssueImporterConfig,
  ModelsUpdateProjectMapping,
  RefreshTags202,
  TestConnectivity200,
  TestExistingConfig200,
} from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
/**
 * @summary Get all importer configurations for organisation (optionally filtered by type)
 */
function getGetConfigsUrl(orgId: string, params?: GetConfigsParams) {
  const normalizedParams = new URLSearchParams()
  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })
  const query = normalizedParams.toString()
  return query
    ? `/organisations/${orgId}/issue-importers` + '?' + query
    : `/organisations/${orgId}/issue-importers`
}

export function useGetConfigs(options?: ApiProxyOptions<ModelsIssueImporterConfigResponse[]>) {
  return useApiProxy<
    ModelsIssueImporterConfigResponse[],
    undefined,
    { orgId: string; params?: GetConfigsParams }
  >(
    {
      getUrl: ({ orgId, params }) => getGetConfigsUrl(orgId, params),
      method: 'GET',
    },
    options,
  )
} /**
 * @summary Create new importer configuration (Organisation Admin only)
 */
export function useCreateConfig(options?: ApiProxyOptions<ModelsIssueImporterConfigResponse>) {
  return useApiProxy<
    ModelsIssueImporterConfigResponse,
    ModelsCreateIssueImporterConfig,
    { orgId: string }
  >(
    {
      getUrl: ({ orgId }) => `/organisations/${orgId}/issue-importers`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary Get importer configuration by ID
 */
export function useGetConfig(options?: ApiProxyOptions<ModelsIssueImporterConfigResponse>) {
  return useApiProxy<
    ModelsIssueImporterConfigResponse,
    undefined,
    { orgId: string; configId: ModelsIssueImporterConfigId }
  >(
    {
      getUrl: ({ orgId, configId }) => `/organisations/${orgId}/issue-importers/${configId}`,
      method: 'GET',
    },
    options,
  )
} /**
 * @summary Update importer configuration (Organisation Admin only)
 */
export function useUpdateConfig(options?: ApiProxyOptions<ModelsIssueImporterConfigResponse>) {
  return useApiProxy<
    ModelsIssueImporterConfigResponse,
    ModelsUpdateIssueImporterConfig,
    { orgId: string; configId: ModelsIssueImporterConfigId }
  >(
    {
      getUrl: ({ orgId, configId }) => `/organisations/${orgId}/issue-importers/${configId}`,
      method: 'PUT',
    },
    options,
  )
} /**
 * @summary Delete importer configuration (Organisation Admin only)
 */
export function useDeleteConfig(options?: ApiProxyOptions<void>) {
  return useApiProxy<void, undefined, { orgId: string; configId: ModelsIssueImporterConfigId }>(
    {
      getUrl: ({ orgId, configId }) => `/organisations/${orgId}/issue-importers/${configId}`,
      method: 'DELETE',
    },
    options,
  )
} /**
 * @summary Get importer configuration for a specific project
 */
export function useGetConfigForProject(
  options?: ApiProxyOptions<ModelsIssueImporterConfigResponse>,
) {
  return useApiProxy<
    ModelsIssueImporterConfigResponse,
    undefined,
    { orgId: string; projectId: string }
  >(
    {
      getUrl: ({ orgId, projectId }) =>
        `/organisations/${orgId}/projects/${projectId}/issue-importer`,
      method: 'GET',
    },
    options,
  )
} /**
 * Tests connectivity to GitLab/Jira/Plane without saving configuration. Useful for validating credentials before creating a config. Requires only OrganisationMember role since nothing is saved.
 * @summary Test connectivity to external service
 */
export function useTestConnectivity(options?: ApiProxyOptions<TestConnectivity200>) {
  return useApiProxy<TestConnectivity200, ModelsCreateIssueImporterConfig, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/organisations/${orgId}/issue-importers/test`,
      method: 'POST',
    },
    options,
  )
} /**
 * Tests connectivity to external service using credentials from an existing saved configuration. Useful for validating that saved credentials still work or testing after updating configuration. Requires only OrganisationMember role since nothing is modified.
 * @summary Test connectivity for existing configuration
 */
export function useTestExistingConfig(options?: ApiProxyOptions<TestExistingConfig200>) {
  return useApiProxy<
    TestExistingConfig200,
    undefined,
    { orgId: string; configId: ModelsIssueImporterConfigId }
  >(
    {
      getUrl: ({ orgId, configId }) => `/organisations/${orgId}/issue-importers/${configId}/test`,
      method: 'POST',
    },
    options,
  )
} /**
 * Fetches list of accessible projects from the configured external service (GitLab/Jira/Plane/GitHub). Returns flat list of projects with id and name for all importer types. The labels and states of one project come from getExternalProjectMetadata. Requires only OrganisationMember role since it only reads from external API.
 * @summary List available projects from external service
 */
export function useListProjects(options?: ApiProxyOptions<ModelsListProjectsResponse>) {
  return useApiProxy<
    ModelsListProjectsResponse,
    undefined,
    { orgId: string; configId: ModelsIssueImporterConfigId }
  >(
    {
      getUrl: ({ orgId, configId }) =>
        `/organisations/${orgId}/issue-importers/${configId}/projects`,
      method: 'GET',
    },
    options,
  )
} /**
 * @summary Add project mapping to configuration (Organisation Admin only)
 */
export function useAddProjectMapping(options?: ApiProxyOptions<ModelsIssueImporterConfigResponse>) {
  return useApiProxy<
    ModelsIssueImporterConfigResponse,
    ModelsCreateProjectMapping,
    { orgId: string; configId: ModelsIssueImporterConfigId }
  >(
    {
      getUrl: ({ orgId, configId }) =>
        `/organisations/${orgId}/issue-importers/${configId}/projects`,
      method: 'POST',
    },
    options,
  )
} /**
 * Fetches the labels and states that the tag filter of a project mapping offers for one external project. GitLab states are "opened", "closed", "all". GitHub states are "open", "closed", "all". Plane states are custom per project. Jira returns empty lists. The external project id is a query parameter, because a GitHub id such as owner/repo contains a slash. Requires only OrganisationMember role since it only reads from external API.
 * @summary Get the labels and states of one external project
 */
function getGetExternalProjectMetadataUrl(
  orgId: string,
  configId: string,
  params?: GetExternalProjectMetadataParams,
) {
  const normalizedParams = new URLSearchParams()
  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })
  const query = normalizedParams.toString()
  return query
    ? `/organisations/${orgId}/issue-importers/${configId}/project-metadata` + '?' + query
    : `/organisations/${orgId}/issue-importers/${configId}/project-metadata`
}

export function useGetExternalProjectMetadata(
  options?: ApiProxyOptions<ModelsExternalProjectMetadata>,
) {
  return useApiProxy<
    ModelsExternalProjectMetadata,
    undefined,
    {
      orgId: string
      configId: ModelsIssueImporterConfigId
      params?: GetExternalProjectMetadataParams
    }
  >(
    {
      getUrl: ({ orgId, configId, params }) =>
        getGetExternalProjectMetadataUrl(orgId, configId, params),
      method: 'GET',
    },
    options,
  )
} /**
 * Lists available resource owners for a GitHub token. Returns the authenticated user plus all organizations they have access to. This helps users select the correct resource owner when creating organization-scoped fine-grained tokens. GitHub-specific endpoint.
 * @summary List GitHub resource owners (user + organizations)
 */
export function useListGithubResourceOwners(options?: ApiProxyOptions<ModelsListProjectsResponse>) {
  return useApiProxy<
    ModelsListProjectsResponse,
    ModelsCreateIssueImporterConfig,
    { orgId: string }
  >(
    {
      getUrl: ({ orgId }) => `/organisations/${orgId}/issue-importers/github/resource-owners`,
      method: 'POST',
    },
    options,
  )
} /**
 * Triggers an immediate tag refresh for a specific project mapping. Sends a message to the worker to fetch tags from the external service (GitLab/Jira/Plane/GitHub) right away, bypassing the scheduled check interval. Tags will be updated within seconds. Requires only OrganisationMember role as this is a read-like operation.
 * @summary Force immediate tag refresh for a project
 */
export function useRefreshTags(options?: ApiProxyOptions<RefreshTags202>) {
  return useApiProxy<
    RefreshTags202,
    undefined,
    { orgId: string; configId: ModelsIssueImporterConfigId; mappingId: ModelsProjectMappingId }
  >(
    {
      getUrl: ({ orgId, configId, mappingId }) =>
        `/organisations/${orgId}/issue-importers/${configId}/projects/${mappingId}/refresh-tags`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary Update project mapping in configuration (Organisation Admin only)
 */
export function useUpdateProjectMapping(
  options?: ApiProxyOptions<ModelsIssueImporterConfigResponse>,
) {
  return useApiProxy<
    ModelsIssueImporterConfigResponse,
    ModelsUpdateProjectMapping,
    { orgId: string; configId: ModelsIssueImporterConfigId; mappingId: ModelsProjectMappingId }
  >(
    {
      getUrl: ({ orgId, configId, mappingId }) =>
        `/organisations/${orgId}/issue-importers/${configId}/projects/${mappingId}`,
      method: 'PUT',
    },
    options,
  )
} /**
 * @summary Remove project mapping from configuration (Organisation Admin only)
 */
export function useRemoveProjectMapping(
  options?: ApiProxyOptions<ModelsIssueImporterConfigResponse>,
) {
  return useApiProxy<
    ModelsIssueImporterConfigResponse,
    undefined,
    { orgId: string; configId: ModelsIssueImporterConfigId; mappingId: ModelsProjectMappingId }
  >(
    {
      getUrl: ({ orgId, configId, mappingId }) =>
        `/organisations/${orgId}/issue-importers/${configId}/projects/${mappingId}`,
      method: 'DELETE',
    },
    options,
  )
}
