/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type {
  ModelsCreateOrganisation,
  ModelsInvitationResult,
  ModelsOrganisation,
  ModelsUpdateOrganisation,
  ModelsUserStub,
  ModelsUserToOrganisationAssignment,
} from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
/**
 * @summary create an organisation
 */
export function useCreateOrganisation(options?: ApiProxyOptions<ModelsOrganisation>) {
  return useApiProxy<ModelsOrganisation, ModelsCreateOrganisation>(
    {
      getUrl: () => `/organisations`,
      method: 'POST',
    },
    options,
  )
}
export function useGetOrganisation(options?: ApiProxyOptions<ModelsOrganisation>) {
  return useApiProxy<ModelsOrganisation, undefined, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/organisations/${orgId}`,
      method: 'GET',
    },
    options,
  )
} /**
 * @summary update an organisation
 */
export function useUpdateOrganisation(options?: ApiProxyOptions<ModelsOrganisation>) {
  return useApiProxy<ModelsOrganisation, ModelsUpdateOrganisation, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/organisations/${orgId}`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary delete/deactivate an organisation
 */
export function useDeactivateOrganisation(options?: ApiProxyOptions<void>) {
  return useApiProxy<void, undefined, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/organisations/${orgId}`,
      method: 'DELETE',
    },
    options,
  )
}
export function useGetOrganisationUserList(options?: ApiProxyOptions<ModelsUserStub[]>) {
  return useApiProxy<ModelsUserStub[], undefined, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/organisations/${orgId}/users`,
      method: 'GET',
    },
    options,
  )
} /**
 * @summary assign a user to an organisation
 */
export function useInviteOrganisationUser(options?: ApiProxyOptions<ModelsInvitationResult>) {
  return useApiProxy<ModelsInvitationResult, ModelsUserToOrganisationAssignment, { orgId: string }>(
    {
      getUrl: ({ orgId }) => `/organisations/${orgId}/invite`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary Remove selected user's membership from selected organisation
 */
export function useRemoveOrganisationUser(options?: ApiProxyOptions<void>) {
  return useApiProxy<void, undefined, { orgId: string; userId: string }>(
    {
      getUrl: ({ orgId, userId }) => `/organisations/${orgId}/users/${userId}`,
      method: 'DELETE',
    },
    options,
  )
}
