/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { GetAggregatedStatisticsByProjectGranularity } from './getAggregatedStatisticsByProjectGranularity'

export type GetAggregatedStatisticsByProjectParams = {
  source: string
  /**
   * @pattern yyyy-MM-dd
   */
  from: string
  /**
   * @pattern yyyy-MM-dd
   */
  to: string
  granularity: GetAggregatedStatisticsByProjectGranularity
}
