/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import type { GetAggregatedStatisticsByProjectGranularity } from './getAggregatedStatisticsByProjectGranularity'

export type GetAggregatedStatisticsByProjectParams = {
	source: string
	/**
	 * @pattern yyyy-MM-dd
	 */
	from: string
	/**
	 * @pattern yyyy-MM-dd
	 */
	to: string
	granularity: GetAggregatedStatisticsByProjectGranularity
}
