/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { GetConfigsType } from './getConfigsType'

export type GetConfigsParams = {
  /**
   * Filter by importer type (gitlab, jira, or plane)
   * @nullable
   */
  type?: GetConfigsType
}
