/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */

export type GetConfigsType =
  | (typeof GetConfigsType)[keyof typeof GetConfigsType]
  | null

export const GetConfigsType = {
  gitlab: 'gitlab',
  jira: 'jira',
  plane: 'plane',
} as const
