/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */

export type GetOrganisationBookingAggregatedStatsGranularity = typeof GetOrganisationBookingAggregatedStatsGranularity[keyof typeof GetOrganisationBookingAggregatedStatsGranularity];


export const GetOrganisationBookingAggregatedStatsGranularity = {
  All: 'All',
  Year: 'Year',
  Month: 'Month',
  Week: 'Week',
  Day: 'Day',
} as const;
