/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */

export type GetProjectBookingListParams = {
  /**
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSS
   */
  from: string
  /**
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSS
   */
  to: string
  /**
   * @nullable
   */
  limit?: number | null
  /**
   * @nullable
   */
  skip?: number | null
}
