/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import type { GetUserBookingAggregatedStatsByOrganisationGranularity } from './getUserBookingAggregatedStatsByOrganisationGranularity'

export type GetUserBookingAggregatedStatsByOrganisationParams = {
  source: string
  /**
   * @pattern yyyy-MM-dd
   */
  from: string
  /**
   * @pattern yyyy-MM-dd
   */
  to: string
  granularity: GetUserBookingAggregatedStatsByOrganisationGranularity
}
