/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */

export type ListGithubResourceOwners400Status =
	(typeof ListGithubResourceOwners400Status)[keyof typeof ListGithubResourceOwners400Status]

export const ListGithubResourceOwners400Status = {
	error: 'error',
} as const
