/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { ListGithubResourceOwners400Status } from './listGithubResourceOwners400Status'
import type { ListGithubResourceOwners400Error } from './listGithubResourceOwners400Error'

export type ListGithubResourceOwners400 = {
	status?: ListGithubResourceOwners400Status
	message?: string
	error?: ListGithubResourceOwners400Error
}
