/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */

export type ListGithubResourceOwners400Error =
	(typeof ListGithubResourceOwners400Error)[keyof typeof ListGithubResourceOwners400Error]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListGithubResourceOwners400Error = {
	list_resource_owners_failed: 'list_resource_owners_failed',
	missing_access_token: 'missing_access_token',
	invalid_importer_type: 'invalid_importer_type',
} as const
