/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import type { ListGithubResourceOwners400Error } from './listGithubResourceOwners400Error'
import type { ListGithubResourceOwners400Status } from './listGithubResourceOwners400Status'

export type ListGithubResourceOwners400 = {
	status?: ListGithubResourceOwners400Status
	message?: string
	error?: ListGithubResourceOwners400Error
}
