/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */

export type ListProjects400Error = typeof ListProjects400Error[keyof typeof ListProjects400Error];


export const ListProjects400Error = {
  list_projects_failed: 'list_projects_failed',
} as const;
