/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { ListGithubResourceOwners400Error } from './listGithubResourceOwners400Error'
import type { ListGithubResourceOwners400Status } from './listGithubResourceOwners400Status'

export type ListGithubResourceOwners400 = {
  status?: ListGithubResourceOwners400Status
  message?: string
  error?: ListGithubResourceOwners400Error
}
