/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { ListProjects400Status } from './listProjects400Status'
import type { ListProjects400Error } from './listProjects400Error'

export type ListProjects400 = {
	status?: ListProjects400Status
	message?: string
	error?: ListProjects400Error
}
