/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import type { ModelsAuditInfoResponse } from './modelsAuditInfoResponse'
import type { ModelsConfigSyncStatus } from './modelsConfigSyncStatus'
import type { ModelsIssueImporterConfigId } from './modelsIssueImporterConfigId'
import type { ModelsPlaneConfigResponseImporterType } from './modelsPlaneConfigResponseImporterType'
import type { ModelsPlaneProjectMapping } from './modelsPlaneProjectMapping'

export interface ModelsPlaneConfigResponse {
  id: ModelsIssueImporterConfigId
  importerType: ModelsPlaneConfigResponseImporterType
  name: string
  baseUrl: string
  checkFrequency: number
  projects: ModelsPlaneProjectMapping[]
  syncStatus: ModelsConfigSyncStatus
  audit: ModelsAuditInfoResponse
  workspace?: string
  type?: string
  projectCount: number
}
