/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import type { ModelsSimpleTag } from './modelsSimpleTag'

export interface ModelsPlaneIssueTag {
  id: string
  projectId: string
  /** @nullable */
  summary?: string | null
  relatedTags: ModelsSimpleTag[]
  issueLink: string
  type: string
}
