/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */
import type { ModelsOAuthUserId } from './modelsOAuthUserId'

export interface ModelsOAuthUser {
  id: ModelsOAuthUserId
  email: string
  password: string
  /** @nullable */
  firstName?: string | null
  /** @nullable */
  lastName?: string | null
  active: boolean
}
