/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type ModelsGitlabTagConfiguration } from './modelsGitlabTagConfiguration'

export interface ModelsGitlabProjectSettings {
	/** @nullable */
	externalProjectName?: null | string
	gitlabProjectId: string
	/** @nullable */
	maxResults?: null | number
	/** @nullable */
	params?: null | string
	/** @nullable */
	projectKeyPrefix?: null | string
	tagConfiguration: ModelsGitlabTagConfiguration
}
