/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */

/**
 * Health status of connection to external service
 */
export type ModelsConnectivityStatus = typeof ModelsConnectivityStatus[keyof typeof ModelsConnectivityStatus];


export const ModelsConnectivityStatus = {
  healthy: 'healthy',
  degraded: 'degraded',
  failed: 'failed',
  unknown: 'unknown',
} as const;
