/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */
import type { ModelsExternalProject } from './modelsExternalProject'
import type { ModelsExternalWorkspace } from './modelsExternalWorkspace'

export interface ModelsListProjectsResponse {
  /** @nullable */
  projects?: ModelsExternalProject[] | null
  /** @nullable */
  workspaces?: ModelsExternalWorkspace[] | null
}
