/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */

/**
 * Type of the resource owner (User or Organization)
 * @nullable
 */
export type ModelsUpdateIssueImporterConfigResourceOwnerType =
  | (typeof ModelsUpdateIssueImporterConfigResourceOwnerType)[keyof typeof ModelsUpdateIssueImporterConfigResourceOwnerType]
  | null

export const ModelsUpdateIssueImporterConfigResourceOwnerType = {
  User: 'User',
  Organization: 'Organization',
} as const
