/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { ModelsIssueImporterConfigId } from './modelsIssueImporterConfigId'
import type { ModelsJiraConfigResponseImporterType } from './modelsJiraConfigResponseImporterType'
import type { ModelsJiraProjectMapping } from './modelsJiraProjectMapping'
import type { ModelsConfigSyncStatus } from './modelsConfigSyncStatus'
import type { ModelsAuditInfoResponse } from './modelsAuditInfoResponse'

export interface ModelsJiraConfigResponse {
	id: ModelsIssueImporterConfigId
	importerType: ModelsJiraConfigResponseImporterType
	name: string
	baseUrl: string
	checkFrequency: number
	projects: ModelsJiraProjectMapping[]
	syncStatus: ModelsConfigSyncStatus
	audit: ModelsAuditInfoResponse
	type?: string
	projectCount: number
}
