/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { ModelsAcceptedTOS } from './modelsAcceptedTOS'
import type { ModelsUserOrganisation } from './modelsUserOrganisation'
import type { ModelsUserRole } from './modelsUserRole'
import type { ModelsUserSettings } from './modelsUserSettings'

export interface ModelsUser {
  id: string
  key: string
  email: string
  firstName: string
  lastName: string
  active: boolean
  role: ModelsUserRole
  organisations: ModelsUserOrganisation[]
  settings: ModelsUserSettings
  acceptedTOS?: ModelsAcceptedTOS | null
}
