/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */

export type ModelsUserRole = typeof ModelsUserRole[keyof typeof ModelsUserRole];


export const ModelsUserRole = {
  FreeUser: 'FreeUser',
  Administrator: 'Administrator',
} as const;
