/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsEntityReferenceModelsUserId } from './modelsEntityReferenceModelsUserId'
import type { ModelsTag } from './modelsTag'

export interface ModelsProject {
  id: string
  key: string
  organisationReference: ModelsEntityReference
  bookingCategories: ModelsTag[]
  active: boolean
  createdBy: ModelsEntityReference
  deactivatedBy?: ModelsEntityReferenceModelsUserId | null
}
