/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */

/**
 * Type of the resource owner (User or Organization)
 * @nullable
 */
export type ModelsGithubConfigResponseResourceOwnerType =
  | (typeof ModelsGithubConfigResponseResourceOwnerType)[keyof typeof ModelsGithubConfigResponseResourceOwnerType]
  | null

export const ModelsGithubConfigResponseResourceOwnerType = {
  User: 'User',
  Organization: 'Organization',
} as const
