/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */

export interface ModelsJiraProjectSettings {
  jiraProjectKey: string
  /** @nullable */
  externalProjectName?: string | null
  /** @nullable */
  maxResults?: number | null
  /** @nullable */
  jql?: string | null
}
