/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */

export type ModelsInvitationOutcomeStatus = typeof ModelsInvitationOutcomeStatus[keyof typeof ModelsInvitationOutcomeStatus];


export const ModelsInvitationOutcomeStatus = {
  InvitationAccepted: 'InvitationAccepted',
  InvitationDeclined: 'InvitationDeclined',
} as const;
