/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsLocalDateTimeWithTimeZone } from './modelsLocalDateTimeWithTimeZone'
import type { ModelsTag } from './modelsTag'

export interface ModelsBooking {
  id: string
  start: ModelsLocalDateTimeWithTimeZone
  end?: ModelsLocalDateTimeWithTimeZone | null
  userReference: ModelsEntityReference
  organisationReference: ModelsEntityReference
  projectReference: ModelsEntityReference
  tags: ModelsTag[]
  bookingHash: number
}
