/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { ModelsGithubIssueTagType } from './modelsGithubIssueTagType'
import type { ModelsSimpleTag } from './modelsSimpleTag'

export interface ModelsGithubIssueTag {
  id: string
  repoOwner: string
  repoName: string
  issueNumber: number
  /** @nullable */
  summary?: string | null
  relatedTags: ModelsSimpleTag[]
  issueLink: string
  type: ModelsGithubIssueTagType
}
