/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsJoinOrganisationInvitationRole } from './modelsJoinOrganisationInvitationRole'
import type { ModelsInvitationOutcome } from './modelsInvitationOutcome'
import type { ModelsJoinOrganisationInvitationType } from './modelsJoinOrganisationInvitationType'

export interface ModelsJoinOrganisationInvitation {
	id: string
	invitedEmail: string
	/** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
	createDate: string
	createdBy: ModelsEntityReference
	/** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
	expiration: string
	organisationReference: ModelsEntityReference
	role: ModelsJoinOrganisationInvitationRole
	/** @nullable */
	outcome?: ModelsInvitationOutcome
	type: ModelsJoinOrganisationInvitationType
}
