/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import type { ModelsUpdateIssueImporterConfigResourceOwnerType } from './modelsUpdateIssueImporterConfigResourceOwnerType'

export interface ModelsUpdateIssueImporterConfig {
  /** @nullable */
  name?: string | null
  /** @nullable */
  baseUrl?: string | null
  /** @nullable */
  checkFrequency?: number | null
  /** @nullable */
  accessToken?: string | null
  /** @nullable */
  consumerKey?: string | null
  /** @nullable */
  privateKey?: string | null
  /** @nullable */
  apiKey?: string | null
  /** @nullable */
  workspace?: string | null
  /**
   * GitHub resource owner (organization or user login) for the token
   * @nullable
   */
  resourceOwner?: string | null
  /**
   * Type of the resource owner (User or Organization)
   * @nullable
   */
  resourceOwnerType?: ModelsUpdateIssueImporterConfigResourceOwnerType
}
