/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */

/**
 * Type of the resource owner (User or Organization)
 * @nullable
 */
export type ModelsUpdateIssueImporterConfigResourceOwnerType =
	| null
	| (typeof ModelsUpdateIssueImporterConfigResourceOwnerType)[keyof typeof ModelsUpdateIssueImporterConfigResourceOwnerType]

export const ModelsUpdateIssueImporterConfigResourceOwnerType = {
	Organization: 'Organization',
	User: 'User',
} as const
