/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsUserOrganisationRole } from './modelsUserOrganisationRole'
import type { ModelsUserProject } from './modelsUserProject'
import type { ModelsWorkingHours } from './modelsWorkingHours'

export interface ModelsUserOrganisation {
  organisationReference: ModelsEntityReference
  private: boolean
  role: ModelsUserOrganisationRole
  plannedWorkingHours: ModelsWorkingHours
  projects: ModelsUserProject[]
}
