/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { ModelsJoinOrganisationInvitation } from './modelsJoinOrganisationInvitation'
import type { ModelsJoinProjectInvitation } from './modelsJoinProjectInvitation'

export type ModelsInvitation =
  | (ModelsJoinOrganisationInvitation & unknown)
  | (ModelsJoinProjectInvitation & unknown)
