/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { ModelsAuditInfoResponse } from './modelsAuditInfoResponse'
import type { ModelsConfigSyncStatus } from './modelsConfigSyncStatus'
import type { ModelsIssueImporterConfigId } from './modelsIssueImporterConfigId'
import type { ModelsJiraConfigResponseImporterType } from './modelsJiraConfigResponseImporterType'
import type { ModelsJiraProjectMapping } from './modelsJiraProjectMapping'

export interface ModelsJiraConfigResponse {
  id: ModelsIssueImporterConfigId
  importerType: ModelsJiraConfigResponseImporterType
  name: string
  baseUrl: string
  checkFrequency: number
  projects: ModelsJiraProjectMapping[]
  syncStatus: ModelsConfigSyncStatus
  audit: ModelsAuditInfoResponse
  type?: string
  projectCount: number
}
