/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */

/**
 * Type of the resource owner (User or Organization)
 * @nullable
 */
export type ModelsGithubConfigResponseResourceOwnerType =
	| (typeof ModelsGithubConfigResponseResourceOwnerType)[keyof typeof ModelsGithubConfigResponseResourceOwnerType]
	| null

export const ModelsGithubConfigResponseResourceOwnerType = {
	User: 'User',
	Organization: 'Organization',
} as const
