/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { ModelsAuditInfoResponse } from './modelsAuditInfoResponse'
import type { ModelsConfigSyncStatus } from './modelsConfigSyncStatus'
import type { ModelsGitlabConfigResponseImporterType } from './modelsGitlabConfigResponseImporterType'
import type { ModelsGitlabProjectMapping } from './modelsGitlabProjectMapping'
import type { ModelsIssueImporterConfigId } from './modelsIssueImporterConfigId'

export interface ModelsGitlabConfigResponse {
  id: ModelsIssueImporterConfigId
  importerType: ModelsGitlabConfigResponseImporterType
  name: string
  baseUrl: string
  checkFrequency: number
  projects: ModelsGitlabProjectMapping[]
  syncStatus: ModelsConfigSyncStatus
  audit: ModelsAuditInfoResponse
  type?: string
  projectCount: number
}
