/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */

/**
 * Type of the resource owner (GitHub only, User or Organization)
 * @nullable
 */
export type ModelsExternalProjectOwnerType =
	| (typeof ModelsExternalProjectOwnerType)[keyof typeof ModelsExternalProjectOwnerType]
	| null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsExternalProjectOwnerType = {
	User: 'User',
	Organization: 'Organization',
} as const
