/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { ModelsGitlabTagConfiguration } from './modelsGitlabTagConfiguration'
import type { ModelsPlaneTagConfiguration } from './modelsPlaneTagConfiguration'
import type { ModelsGithubTagConfiguration } from './modelsGithubTagConfiguration'

export interface ModelsUpdateProjectMapping {
	/** @nullable */
	externalProjectName?: string | null
	/** @nullable */
	gitlabProjectId?: string | null
	/** @nullable */
	projectKeyPrefix?: string | null
	/** @nullable */
	gitlabTagConfig?: ModelsGitlabTagConfiguration
	/** @nullable */
	jiraProjectKey?: string | null
	/** @nullable */
	planeProjectId?: string | null
	/** @nullable */
	planeTagConfig?: ModelsPlaneTagConfiguration
	/** @nullable */
	githubRepoOwner?: string | null
	/** @nullable */
	githubRepoName?: string | null
	/** @nullable */
	githubTagConfig?: ModelsGithubTagConfiguration
	/** @nullable */
	maxResults?: number | null
	/** @nullable */
	params?: string | null
}
