/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import type { ModelsUserStub } from './modelsUserStub'

/**
 * Audit information with full user details for API responses
 */
export interface ModelsAuditInfoResponse {
	createdBy: ModelsUserStub
	/**
	 * Timestamp when entity was created
	 * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
	 */
	createdAt: string
	updatedBy: ModelsUserStub
	/**
	 * Timestamp when entity was last updated
	 * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
	 */
	updatedAt: string
}
