/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */

export interface ModelsBookingStatsCategory {
	/** @nullable */
	year?: number | null
	/** @nullable */
	month?: number | null
	/** @nullable */
	week?: number | null
	/** @nullable */
	day?: number | null
}
