/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { ModelsTag } from './modelsTag'

export interface ModelsAddBookingRequest {
	projectId: string
	tags: ModelsTag[]
	/** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
	start: string
	/** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
	end: string
}
