/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */

export interface ModelsBookingStatsCategory {
	/** @nullable */
	year?: number | null
	/** @nullable */
	month?: number | null
	/** @nullable */
	week?: number | null
	/** @nullable */
	day?: number | null
}
