/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsUserOrganisationRole } from './modelsUserOrganisationRole'
import type { ModelsWorkingHours } from './modelsWorkingHours'
import type { ModelsUserProject } from './modelsUserProject'

export interface ModelsUserOrganisation {
	organisationReference: ModelsEntityReference
	private: boolean
	role: ModelsUserOrganisationRole
	plannedWorkingHours: ModelsWorkingHours
	projects: ModelsUserProject[]
}
