/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */

export type ModelsJoinOrganisationInvitationRole = typeof ModelsJoinOrganisationInvitationRole[keyof typeof ModelsJoinOrganisationInvitationRole];


export const ModelsJoinOrganisationInvitationRole = {
  OrganisationMember: 'OrganisationMember',
  OrganisationAdministrator: 'OrganisationAdministrator',
} as const;
