/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import type { ModelsGithubConfigResponse } from './modelsGithubConfigResponse'
import type { ModelsGitlabConfigResponse } from './modelsGitlabConfigResponse'
import type { ModelsJiraConfigResponse } from './modelsJiraConfigResponse'
import type { ModelsPlaneConfigResponse } from './modelsPlaneConfigResponse'

export type ModelsIssueImporterConfigResponse =
	| (ModelsGitlabConfigResponse & unknown)
	| (ModelsJiraConfigResponse & unknown)
	| (ModelsPlaneConfigResponse & unknown)
	| (ModelsGithubConfigResponse & unknown)
