/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */

export type ModelsUserStubRole =
	(typeof ModelsUserStubRole)[keyof typeof ModelsUserStubRole]

export const ModelsUserStubRole = {
	FreeUser: 'FreeUser',
	Administrator: 'Administrator',
} as const
