/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import type { ModelsGithubTagConfiguration } from './modelsGithubTagConfiguration'

export interface ModelsGithubProjectSettings {
	githubRepoOwner: string
	githubRepoName: string
	/** @nullable */
	externalProjectName?: string | null
	/** @nullable */
	maxResults?: number | null
	/** @nullable */
	params?: string | null
	/** @nullable */
	projectKeyPrefix?: string | null
	tagConfiguration: ModelsGithubTagConfiguration
}
