/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */

export interface ModelsOAuthAuthorizationCodeLoginRequest {
  clientId: string
  email: string
  password: string
  /** @nullable */
  scope?: string | null
  redirectUri: string
  /** @nullable */
  codeChallenge?: string | null
  /** @nullable */
  codeChallengeMethod?: string | null
  /** @nullable */
  state?: string | null
}
