/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */

export type ModelsJoinOrganisationInvitationRole = typeof ModelsJoinOrganisationInvitationRole[keyof typeof ModelsJoinOrganisationInvitationRole];


export const ModelsJoinOrganisationInvitationRole = {
  OrganisationMember: 'OrganisationMember',
  OrganisationAdministrator: 'OrganisationAdministrator',
} as const;
