import { type ModelsGithubIssueTagType } from './modelsGithubIssueTagType'
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type ModelsSimpleTag } from './modelsSimpleTag'

export interface ModelsGithubIssueTag {
	id: string
	issueLink: string
	issueNumber: number
	relatedTags: ModelsSimpleTag[]
	repoName: string
	repoOwner: string
	/** @nullable */
	summary?: null | string
	type: ModelsGithubIssueTagType
}
