/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */

export type ModelsJoinOrganisationInvitationType = typeof ModelsJoinOrganisationInvitationType[keyof typeof ModelsJoinOrganisationInvitationType];


export const ModelsJoinOrganisationInvitationType = {
  JoinOrganisationInvitation: 'JoinOrganisationInvitation',
} as const;
