import { type ModelsGithubIssueTag } from './modelsGithubIssueTag'
import { type ModelsGitlabIssueTag } from './modelsGitlabIssueTag'
import { type ModelsJiraIssueTag } from './modelsJiraIssueTag'
import { type ModelsPlaneIssueTag } from './modelsPlaneIssueTag'
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type ModelsSimpleTag } from './modelsSimpleTag'
import { type ModelsTagGroup } from './modelsTagGroup'

export type ModelsTag =
	| (ModelsGithubIssueTag & unknown)
	| (ModelsGitlabIssueTag & unknown)
	| (ModelsJiraIssueTag & unknown)
	| (ModelsPlaneIssueTag & unknown)
	| (ModelsSimpleTag & unknown)
	| (ModelsTagGroup & unknown)
