/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */

export type ModelsInvitationStatusResponseStatus = typeof ModelsInvitationStatusResponseStatus[keyof typeof ModelsInvitationStatusResponseStatus];


export const ModelsInvitationStatusResponseStatus = {
  UnregisteredUser: 'UnregisteredUser',
  InvitationOk: 'InvitationOk',
} as const;
