/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsEntityReferenceModelsUserId } from './modelsEntityReferenceModelsUserId'

export interface ModelsOrganisation {
  id: string
  key: string
  private: boolean
  active: boolean
  createdBy: ModelsEntityReference
  deactivatedBy?: ModelsEntityReferenceModelsUserId | null
}
