/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */
import type { ModelsGitlabTagConfiguration } from './modelsGitlabTagConfiguration'

export interface ModelsGitlabProjectSettings {
  gitlabProjectId: string
  /** @nullable */
  externalProjectName?: string | null
  /** @nullable */
  maxResults?: number | null
  /** @nullable */
  params?: string | null
  /** @nullable */
  projectKeyPrefix?: string | null
  tagConfiguration: ModelsGitlabTagConfiguration
}
