/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type ModelsConnectivityIssue } from './modelsConnectivityIssue'

/**
 * Sync statistics for a specific project mapping
 */
export interface ModelsProjectSyncStats {
	/** Number of consecutive sync failures (circuit breaker) */
	consecutiveFailures: number
	/** @nullable */
	lastError?: ModelsConnectivityIssue
	/**
	 * Last successful sync timestamp
	 * @nullable
	 * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
	 */
	lastSyncAt?: null | string
	/** Number of issues synced in last run */
	lastSyncIssueCount: number
	/** Project ID */
	projectId: string
	/** Project name */
	projectName: string
	/** Total issues synced since mapping creation */
	totalIssuesSynced: number
}
