/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { ModelsGithubConfigResponse } from './modelsGithubConfigResponse'
import type { ModelsGitlabConfigResponse } from './modelsGitlabConfigResponse'
import type { ModelsJiraConfigResponse } from './modelsJiraConfigResponse'
import type { ModelsPlaneConfigResponse } from './modelsPlaneConfigResponse'

export type ModelsIssueImporterConfigResponse =
  | (ModelsGitlabConfigResponse & unknown)
  | (ModelsJiraConfigResponse & unknown)
  | (ModelsPlaneConfigResponse & unknown)
  | (ModelsGithubConfigResponse & unknown)
