/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */

export type ModelsJoinProjectInvitationType =
	(typeof ModelsJoinProjectInvitationType)[keyof typeof ModelsJoinProjectInvitationType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsJoinProjectInvitationType = {
	JoinProjectInvitation: 'JoinProjectInvitation',
} as const
