/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsEntityReferenceModelsUserId } from './modelsEntityReferenceModelsUserId'

export interface ModelsOrganisation {
	id: string
	key: string
	private: boolean
	active: boolean
	createdBy: ModelsEntityReference
	deactivatedBy?: ModelsEntityReferenceModelsUserId | null
}
