/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */

/**
 * Health status of connection to external service
 */
export type ModelsConnectivityStatus =
	(typeof ModelsConnectivityStatus)[keyof typeof ModelsConnectivityStatus]

export const ModelsConnectivityStatus = {
	healthy: 'healthy',
	degraded: 'degraded',
	failed: 'failed',
	unknown: 'unknown',
} as const
