/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */

export type ModelsImporterType = typeof ModelsImporterType[keyof typeof ModelsImporterType];


export const ModelsImporterType = {
  gitlab: 'gitlab',
  jira: 'jira',
  plane: 'plane',
  github: 'github',
} as const;
