/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import type { ModelsTag } from './modelsTag'

export interface ModelsStartBookingRequest {
  projectId: string
  tags: ModelsTag[]
  /**
   * @nullable
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
   */
  start?: string | null
}
