/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type ModelsUpdateIssueImporterConfigResourceOwnerType } from './modelsUpdateIssueImporterConfigResourceOwnerType'

export interface ModelsUpdateIssueImporterConfig {
	/** @nullable */
	accessToken?: null | string
	/** @nullable */
	apiKey?: null | string
	/** @nullable */
	baseUrl?: null | string
	/** @nullable */
	checkFrequency?: null | number
	/** @nullable */
	consumerKey?: null | string
	/** @nullable */
	name?: null | string
	/** @nullable */
	privateKey?: null | string
	/**
	 * GitHub resource owner (organization or user login) for the token
	 * @nullable
	 */
	resourceOwner?: null | string
	/**
	 * Type of the resource owner (User or Organization)
	 * @nullable
	 */
	resourceOwnerType?: ModelsUpdateIssueImporterConfigResourceOwnerType
	/** @nullable */
	workspace?: null | string
}
