/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { ModelsGitlabProjectMapping } from './modelsGitlabProjectMapping'

export interface ModelsUpdateGitlabConfig {
  name?: string
  baseUrl?: string
  accessToken?: string
  checkFrequency?: number
  projects?: ModelsGitlabProjectMapping[]
}
