/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { ModelsLocalDateTimeWithTimeZone } from './modelsLocalDateTimeWithTimeZone'
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsTag } from './modelsTag'

export interface ModelsBooking {
	id: string
	start: ModelsLocalDateTimeWithTimeZone
	/** @nullable */
	end?: ModelsLocalDateTimeWithTimeZone
	userReference: ModelsEntityReference
	organisationReference: ModelsEntityReference
	projectReference: ModelsEntityReference
	tags: ModelsTag[]
	bookingHash: number
}
