/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type ModelsExternalProjectOwnerType } from './modelsExternalProjectOwnerType'

/**
 * External project or resource owner from an issue tracking system
 */
export interface ModelsExternalProject {
	/** @nullable */
	availableLabels?: null | string[]
	/** @nullable */
	availableStates?: null | string[]
	/** External project ID or resource owner login */
	id: string
	/** Display name of the project or resource owner */
	name: string
	/**
	 * Type of the resource owner (GitHub only, User or Organization)
	 * @nullable
	 */
	ownerType?: ModelsExternalProjectOwnerType
}
