/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsInvitationOutcome } from './modelsInvitationOutcome'
import type { ModelsJoinOrganisationInvitationRole } from './modelsJoinOrganisationInvitationRole'
import type { ModelsJoinOrganisationInvitationType } from './modelsJoinOrganisationInvitationType'

export interface ModelsJoinOrganisationInvitation {
	id: string
	invitedEmail: string
	/** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
	createDate: string
	createdBy: ModelsEntityReference
	/** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
	expiration: string
	organisationReference: ModelsEntityReference
	role: ModelsJoinOrganisationInvitationRole
	outcome?: ModelsInvitationOutcome | null
	type: ModelsJoinOrganisationInvitationType
}
