/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsInvitationOutcome } from './modelsInvitationOutcome'
import type { ModelsJoinOrganisationInvitationRole } from './modelsJoinOrganisationInvitationRole'
import type { ModelsJoinOrganisationInvitationType } from './modelsJoinOrganisationInvitationType'

export interface ModelsJoinOrganisationInvitation {
  id: string
  invitedEmail: string
  /** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
  createDate: string
  createdBy: ModelsEntityReference
  /** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
  expiration: string
  organisationReference: ModelsEntityReference
  role: ModelsJoinOrganisationInvitationRole
  outcome?: ModelsInvitationOutcome | null
  type: ModelsJoinOrganisationInvitationType
}
