/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsInvitationOutcome } from './modelsInvitationOutcome'
import type { ModelsJoinProjectInvitationRole } from './modelsJoinProjectInvitationRole'
import type { ModelsJoinProjectInvitationType } from './modelsJoinProjectInvitationType'

export interface ModelsJoinProjectInvitation {
	id: string
	invitedEmail: string
	/** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
	createDate: string
	createdBy: ModelsEntityReference
	/** @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ */
	expiration: string
	sharedByOrganisationReference: ModelsEntityReference
	projectReference: ModelsEntityReference
	role: ModelsJoinProjectInvitationRole
	outcome?: ModelsInvitationOutcome | null
	type: ModelsJoinProjectInvitationType
}
