/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */
import type { ModelsGithubIssueTag } from './modelsGithubIssueTag'
import type { ModelsGitlabIssueTag } from './modelsGitlabIssueTag'
import type { ModelsJiraIssueTag } from './modelsJiraIssueTag'
import type { ModelsPlaneIssueTag } from './modelsPlaneIssueTag'
import type { ModelsSimpleTag } from './modelsSimpleTag'
import type { ModelsTagGroup } from './modelsTagGroup'

export type ModelsTag =
  | (ModelsSimpleTag & unknown)
  | (ModelsTagGroup & unknown)
  | (ModelsGitlabIssueTag & unknown)
  | (ModelsJiraIssueTag & unknown)
  | (ModelsPlaneIssueTag & unknown)
  | (ModelsGithubIssueTag & unknown)
