/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { ModelsSimpleTag } from './modelsSimpleTag'
import type { ModelsGithubIssueTagType } from './modelsGithubIssueTagType'

export interface ModelsGithubIssueTag {
	id: string
	repoOwner: string
	repoName: string
	issueNumber: number
	/** @nullable */
	summary?: string | null
	relatedTags: ModelsSimpleTag[]
	issueLink: string
	type: ModelsGithubIssueTagType
}
