/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */

/**
 * Type of the resource owner (GitHub only, User or Organization)
 * @nullable
 */
export type ModelsExternalProjectOwnerType =
	| null
	| (typeof ModelsExternalProjectOwnerType)[keyof typeof ModelsExternalProjectOwnerType]

export const ModelsExternalProjectOwnerType = {
	Organization: 'Organization',
	User: 'User',
} as const
