/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */

/**
 * Type of the resource owner (User or Organization)
 * @nullable
 */
export type ModelsUpdateIssueImporterConfigResourceOwnerType =
  | (typeof ModelsUpdateIssueImporterConfigResourceOwnerType)[keyof typeof ModelsUpdateIssueImporterConfigResourceOwnerType]
  | null

export const ModelsUpdateIssueImporterConfigResourceOwnerType = {
  User: 'User',
  Organization: 'Organization',
} as const
