/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */

/**
 * Details about a connectivity or sync error
 */
export interface ModelsConnectivityIssue {
  /** Machine-readable error code */
  errorCode: string
  /** Human-readable error message */
  message: string
  /**
   * When the error occurred
   * @pattern yyyy-MM-dd'T'HH:mm:ss.SSSZZ
   */
  timestamp: string
  /**
   * HTTP status code if applicable
   * @nullable
   */
  httpStatus?: number | null
  /** Number of consecutive retry attempts */
  retryCount: number
}
