/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { ModelsSimpleTag } from './modelsSimpleTag'
import type { ModelsTagGroupType } from './modelsTagGroupType'

export interface ModelsTagGroup {
  id: string
  relatedTags: ModelsSimpleTag[]
  type: ModelsTagGroupType
}
