/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { ModelsExternalProjectOwnerType } from './modelsExternalProjectOwnerType'

/**
 * External project or resource owner from an issue tracking system
 */
export interface ModelsExternalProject {
  /** External project ID or resource owner login */
  id: string
  /** Display name of the project or resource owner */
  name: string
  /**
   * Type of the resource owner (GitHub only, User or Organization)
   * @nullable
   */
  ownerType?: ModelsExternalProjectOwnerType
  /** @nullable */
  availableLabels?: string[] | null
  /** @nullable */
  availableStates?: string[] | null
}
