import { type RefreshTags202ImporterType } from './refreshTags202ImporterType'
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type RefreshTags202Status } from './refreshTags202Status'

export type RefreshTags202 = {
	configId?: string
	importerType?: RefreshTags202ImporterType
	message?: string
	projectId?: string
	status?: RefreshTags202Status
}
