/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { RefreshTags202ImporterType } from './refreshTags202ImporterType'
import type { RefreshTags202Status } from './refreshTags202Status'

export type RefreshTags202 = {
  status?: RefreshTags202Status
  message?: string
  configId?: string
  projectId?: string
  importerType?: RefreshTags202ImporterType
}
