/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import type { RefreshTags404Error } from './refreshTags404Error'
import type { RefreshTags404Status } from './refreshTags404Status'

export type RefreshTags404 = {
  status?: RefreshTags404Status
  message?: string
  error?: RefreshTags404Error
  configId?: string
  projectId?: string
}
