/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */

export type RefreshTags404Status = typeof RefreshTags404Status[keyof typeof RefreshTags404Status];


export const RefreshTags404Status = {
  error: 'error',
} as const;
