/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */

export type RefreshTags202Status = typeof RefreshTags202Status[keyof typeof RefreshTags202Status];


export const RefreshTags202Status = {
  accepted: 'accepted',
} as const;
