/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */

export type RefreshTags404Error = typeof RefreshTags404Error[keyof typeof RefreshTags404Error];


export const RefreshTags404Error = {
  config_not_found: 'config_not_found',
  project_not_found: 'project_not_found',
} as const;
