/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { RefreshTags404Status } from './refreshTags404Status'
import type { RefreshTags404Error } from './refreshTags404Error'

export type RefreshTags404 = {
	status?: RefreshTags404Status
	message?: string
	error?: RefreshTags404Error
	configId?: string
	projectId?: string
}
