/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { TestConnectivity400Status } from './testConnectivity400Status'
import type { TestConnectivity400Error } from './testConnectivity400Error'

export type TestConnectivity400 = {
	status?: TestConnectivity400Status
	message?: string
	error?: TestConnectivity400Error
}
