/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */

export type TestExistingConfig200Status =
	(typeof TestExistingConfig200Status)[keyof typeof TestExistingConfig200Status]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TestExistingConfig200Status = {
	success: 'success',
} as const
