/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */

export type TestConnectivity200Status = typeof TestConnectivity200Status[keyof typeof TestConnectivity200Status];


export const TestConnectivity200Status = {
  success: 'success',
} as const;
