/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */

export type TestConnectivity400Status = typeof TestConnectivity400Status[keyof typeof TestConnectivity400Status];


export const TestConnectivity400Status = {
  error: 'error',
} as const;
