/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */

export type TestConnectivity200Status = typeof TestConnectivity200Status[keyof typeof TestConnectivity200Status];


export const TestConnectivity200Status = {
  success: 'success',
} as const;
