/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */

export type TestConnectivity400Error = typeof TestConnectivity400Error[keyof typeof TestConnectivity400Error];


export const TestConnectivity400Error = {
  connection_failed: 'connection_failed',
  authentication_failed: 'authentication_failed',
  unknown_host: 'unknown_host',
  timeout: 'timeout',
  connection_error: 'connection_error',
  validation_failed: 'validation_failed',
} as const;
