/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { TestExistingConfig200Status } from './testExistingConfig200Status'

export type TestExistingConfig200 = {
  status?: TestExistingConfig200Status
  message?: string
}
