/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */

export type TestConnectivity400Error =
	(typeof TestConnectivity400Error)[keyof typeof TestConnectivity400Error]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TestConnectivity400Error = {
	connection_failed: 'connection_failed',
	authentication_failed: 'authentication_failed',
	unknown_host: 'unknown_host',
	timeout: 'timeout',
	connection_error: 'connection_error',
	validation_failed: 'validation_failed',
} as const
