/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */

export type TestExistingConfig400Status =
	(typeof TestExistingConfig400Status)[keyof typeof TestExistingConfig400Status]

export const TestExistingConfig400Status = {
	error: 'error',
} as const
