/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */

export type TestExistingConfig400Error =
	(typeof TestExistingConfig400Error)[keyof typeof TestExistingConfig400Error]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TestExistingConfig400Error = {
	connection_failed: 'connection_failed',
	authentication_failed: 'authentication_failed',
	unknown_host: 'unknown_host',
	timeout: 'timeout',
	connection_error: 'connection_error',
} as const
