/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { TestConnectivity400Error } from './testConnectivity400Error'
import type { TestConnectivity400Status } from './testConnectivity400Status'

export type TestConnectivity400 = {
  status?: TestConnectivity400Status
  message?: string
  error?: TestConnectivity400Error
}
