/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */

export type TestExistingConfig400Status = typeof TestExistingConfig400Status[keyof typeof TestExistingConfig400Status];


export const TestExistingConfig400Status = {
  error: 'error',
} as const;
