import { type TestExistingConfig400Error } from './testExistingConfig400Error'
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type TestExistingConfig400Status } from './testExistingConfig400Status'

export type TestExistingConfig400 = {
	error?: TestExistingConfig400Error
	message?: string
	status?: TestExistingConfig400Status
}
