/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type TestExistingConfig200Status } from './testExistingConfig200Status'

export type TestExistingConfig200 = {
	message?: string
	status?: TestExistingConfig200Status
}
