/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */

export type TestExistingConfig200Status = typeof TestExistingConfig200Status[keyof typeof TestExistingConfig200Status];


export const TestExistingConfig200Status = {
  success: 'success',
} as const;
