/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */
import type { ModelsConfigSyncStatus } from './modelsConfigSyncStatus'
import type { ModelsImporterType } from './modelsImporterType'
import type { WebSocketIssueImporterSyncStatsChangedType } from './webSocketIssueImporterSyncStatsChangedType'

/**
 * Issue importer sync status changed (admin-only, negative outcomes only)
 */
export interface WebSocketIssueImporterSyncStatsChanged {
  type: WebSocketIssueImporterSyncStatsChangedType
  configId: string
  organisationId: string
  importerType: ModelsImporterType
  configName: string
  syncStatus: ModelsConfigSyncStatus
}
