/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { WebSocketCurrentUserTimeBookingEventType } from './webSocketCurrentUserTimeBookingEventType'
import type { ModelsCurrentUserTimeBooking } from './modelsCurrentUserTimeBooking'

/**
 * Current user's active booking update
 */
export interface WebSocketCurrentUserTimeBookingEvent {
	type: WebSocketCurrentUserTimeBookingEventType
	booking: ModelsCurrentUserTimeBooking
}
