import { type ModelsBookingStub } from './modelsBookingStub'
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type WebSocketLatestTimeBookingType } from './webSocketLatestTimeBookingType'

/**
 * User's recent booking history update
 */
export interface WebSocketLatestTimeBooking {
	history: ModelsBookingStub[]
	type: WebSocketLatestTimeBookingType
	userId: string
}
