/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import type { WebSocketPong } from './webSocketPong'
import type { WebSocketHelloClient } from './webSocketHelloClient'
import type { WebSocketAuthenticationFailed } from './webSocketAuthenticationFailed'
import type { WebSocketCurrentUserTimeBookingEvent } from './webSocketCurrentUserTimeBookingEvent'
import type { WebSocketCurrentOrganisationTimeBookings } from './webSocketCurrentOrganisationTimeBookings'
import type { WebSocketFavoriteAdded } from './webSocketFavoriteAdded'
import type { WebSocketFavoriteRemoved } from './webSocketFavoriteRemoved'
import type { WebSocketLatestTimeBooking } from './webSocketLatestTimeBooking'
import type { WebSocketIssueImporterSyncStatsChanged } from './webSocketIssueImporterSyncStatsChanged'
import type { WebSocketUserTimeBookingHistoryEntryCleaned } from './webSocketUserTimeBookingHistoryEntryCleaned'
import type { WebSocketUserTimeBookingHistoryEntryAdded } from './webSocketUserTimeBookingHistoryEntryAdded'
import type { WebSocketUserTimeBookingHistoryEntryRemoved } from './webSocketUserTimeBookingHistoryEntryRemoved'
import type { WebSocketUserTimeBookingHistoryEntryChanged } from './webSocketUserTimeBookingHistoryEntryChanged'

export type WebSocketOutEvent =
	| WebSocketPong
	| WebSocketHelloClient
	| WebSocketAuthenticationFailed
	| WebSocketCurrentUserTimeBookingEvent
	| WebSocketCurrentOrganisationTimeBookings
	| WebSocketFavoriteAdded
	| WebSocketFavoriteRemoved
	| WebSocketLatestTimeBooking
	| WebSocketIssueImporterSyncStatsChanged
	| WebSocketUserTimeBookingHistoryEntryCleaned
	| WebSocketUserTimeBookingHistoryEntryAdded
	| WebSocketUserTimeBookingHistoryEntryRemoved
	| WebSocketUserTimeBookingHistoryEntryChanged
