import { type ModelsBooking } from './modelsBooking'
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type WebSocketUserTimeBookingHistoryEntryAddedType } from './webSocketUserTimeBookingHistoryEntryAddedType'

/**
 * New booking added to user's history
 */
export interface WebSocketUserTimeBookingHistoryEntryAdded {
	booking: ModelsBooking
	type: WebSocketUserTimeBookingHistoryEntryAddedType
}
