/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { ModelsCurrentUserTimeBooking } from './modelsCurrentUserTimeBooking'
import type { WebSocketCurrentUserTimeBookingEventType } from './webSocketCurrentUserTimeBookingEventType'

/**
 * Current user's active booking update
 */
export interface WebSocketCurrentUserTimeBookingEvent {
  type: WebSocketCurrentUserTimeBookingEventType
  booking: ModelsCurrentUserTimeBooking
}
