import { type ModelsConfigSyncStatus } from './modelsConfigSyncStatus'
import { type ModelsImporterType } from './modelsImporterType'
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type WebSocketIssueImporterSyncStatsChangedType } from './webSocketIssueImporterSyncStatsChangedType'

/**
 * Issue importer sync status changed (admin-only, negative outcomes only)
 */
export interface WebSocketIssueImporterSyncStatsChanged {
	configId: string
	configName: string
	importerType: ModelsImporterType
	organisationId: string
	syncStatus: ModelsConfigSyncStatus
	type: WebSocketIssueImporterSyncStatsChangedType
}
