/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import type { ModelsCurrentUserTimeBooking } from './modelsCurrentUserTimeBooking'
import type { WebSocketCurrentOrganisationTimeBookingsType } from './webSocketCurrentOrganisationTimeBookingsType'

/**
 * Current time bookings for all users in an organization
 */
export interface WebSocketCurrentOrganisationTimeBookings {
  type: WebSocketCurrentOrganisationTimeBookingsType
  orgId: string
  timeBookings: ModelsCurrentUserTimeBooking[]
}
