/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */

export type WebSocketUserTimeBookingHistoryEntryRemovedType = typeof WebSocketUserTimeBookingHistoryEntryRemovedType[keyof typeof WebSocketUserTimeBookingHistoryEntryRemovedType];


export const WebSocketUserTimeBookingHistoryEntryRemovedType = {
  UserTimeBookingHistoryEntryRemoved: 'UserTimeBookingHistoryEntryRemoved',
} as const;
