/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import type { ModelsBookingStub } from './modelsBookingStub'
import type { WebSocketFavoriteRemovedType } from './webSocketFavoriteRemovedType'

/**
 * User removed a booking from favorites
 */
export interface WebSocketFavoriteRemoved {
  type: WebSocketFavoriteRemovedType
  userId: string
  orgId: string
  bookingStub: ModelsBookingStub
}
