/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { WebSocketAuthenticationFailed } from './webSocketAuthenticationFailed'
import type { WebSocketCurrentOrganisationTimeBookings } from './webSocketCurrentOrganisationTimeBookings'
import type { WebSocketCurrentUserTimeBookingEvent } from './webSocketCurrentUserTimeBookingEvent'
import type { WebSocketFavoriteAdded } from './webSocketFavoriteAdded'
import type { WebSocketFavoriteRemoved } from './webSocketFavoriteRemoved'
import type { WebSocketHelloClient } from './webSocketHelloClient'
import type { WebSocketIssueImporterSyncStatsChanged } from './webSocketIssueImporterSyncStatsChanged'
import type { WebSocketLatestTimeBooking } from './webSocketLatestTimeBooking'
import type { WebSocketPong } from './webSocketPong'
import type { WebSocketUserTimeBookingHistoryEntryAdded } from './webSocketUserTimeBookingHistoryEntryAdded'
import type { WebSocketUserTimeBookingHistoryEntryChanged } from './webSocketUserTimeBookingHistoryEntryChanged'
import type { WebSocketUserTimeBookingHistoryEntryCleaned } from './webSocketUserTimeBookingHistoryEntryCleaned'
import type { WebSocketUserTimeBookingHistoryEntryRemoved } from './webSocketUserTimeBookingHistoryEntryRemoved'

export type WebSocketOutEvent =
  | WebSocketPong
  | WebSocketHelloClient
  | WebSocketAuthenticationFailed
  | WebSocketCurrentUserTimeBookingEvent
  | WebSocketCurrentOrganisationTimeBookings
  | WebSocketFavoriteAdded
  | WebSocketFavoriteRemoved
  | WebSocketLatestTimeBooking
  | WebSocketIssueImporterSyncStatsChanged
  | WebSocketUserTimeBookingHistoryEntryCleaned
  | WebSocketUserTimeBookingHistoryEntryAdded
  | WebSocketUserTimeBookingHistoryEntryRemoved
  | WebSocketUserTimeBookingHistoryEntryChanged
