/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */

export type WebSocketUserTimeBookingHistoryEntryChangedType = typeof WebSocketUserTimeBookingHistoryEntryChangedType[keyof typeof WebSocketUserTimeBookingHistoryEntryChangedType];


export const WebSocketUserTimeBookingHistoryEntryChangedType = {
  UserTimeBookingHistoryEntryChanged: 'UserTimeBookingHistoryEntryChanged',
} as const;
