/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import type { ModelsCurrentUserTimeBooking } from './modelsCurrentUserTimeBooking'
import type { WebSocketCurrentOrganisationTimeBookingsType } from './webSocketCurrentOrganisationTimeBookingsType'

/**
 * Current time bookings for all users in an organization
 */
export interface WebSocketCurrentOrganisationTimeBookings {
	type: WebSocketCurrentOrganisationTimeBookingsType
	orgId: string
	timeBookings: ModelsCurrentUserTimeBooking[]
}
