/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import type { ModelsBookingStub } from './modelsBookingStub'
import type { WebSocketFavoriteAddedType } from './webSocketFavoriteAddedType'

/**
 * User added a booking to favorites
 */
export interface WebSocketFavoriteAdded {
	type: WebSocketFavoriteAddedType
	userId: string
	orgId: string
	bookingStub: ModelsBookingStub
}
