/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import type { ModelsBooking } from './modelsBooking'
import type { WebSocketUserTimeBookingHistoryEntryChangedType } from './webSocketUserTimeBookingHistoryEntryChangedType'

/**
 * Existing booking in user's history was modified
 */
export interface WebSocketUserTimeBookingHistoryEntryChanged {
	type: WebSocketUserTimeBookingHistoryEntryChangedType
	booking: ModelsBooking
}
