/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { ModelsBookingStub } from './modelsBookingStub'
import type { WebSocketLatestTimeBookingType } from './webSocketLatestTimeBookingType'

/**
 * User's recent booking history update
 */
export interface WebSocketLatestTimeBooking {
  type: WebSocketLatestTimeBookingType
  userId: string
  history: ModelsBookingStub[]
}
