/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+43-e7b745c1+20260321-2204
 */
import type { ModelsConfigSyncStatus } from './modelsConfigSyncStatus'
import type { ModelsImporterType } from './modelsImporterType'
import type { WebSocketIssueImporterSyncStatsChangedType } from './webSocketIssueImporterSyncStatsChangedType'

/**
 * Issue importer sync status changed (admin-only, negative outcomes only)
 */
export interface WebSocketIssueImporterSyncStatsChanged {
	type: WebSocketIssueImporterSyncStatsChangedType
	configId: string
	organisationId: string
	importerType: ModelsImporterType
	configName: string
	syncStatus: ModelsConfigSyncStatus
}
