/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+103-fab637e0+20260323-1007
 */
import type { ModelsBookingStub } from './modelsBookingStub'
import type { WebSocketFavoriteRemovedType } from './webSocketFavoriteRemovedType'

/**
 * User removed a booking from favorites
 */
export interface WebSocketFavoriteRemoved {
  type: WebSocketFavoriteRemovedType
  userId: string
  orgId: string
  bookingStub: ModelsBookingStub
}
