/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+109-0a77adda+20260323-1323
 */
import type { ModelsBooking } from './modelsBooking'
import type { WebSocketUserTimeBookingHistoryEntryChangedType } from './webSocketUserTimeBookingHistoryEntryChangedType'

/**
 * Existing booking in user's history was modified
 */
export interface WebSocketUserTimeBookingHistoryEntryChanged {
  type: WebSocketUserTimeBookingHistoryEntryChangedType
  booking: ModelsBooking
}
