/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { ModelsBookingStub } from './modelsBookingStub'
import type { WebSocketFavoriteAddedType } from './webSocketFavoriteAddedType'

/**
 * User added a booking to favorites
 */
export interface WebSocketFavoriteAdded {
  type: WebSocketFavoriteAddedType
  userId: string
  orgId: string
  bookingStub: ModelsBookingStub
}
