/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type {
  GetAggregatedStatisticsByProjectParams,
  GetProjectBookingListParams,
  ModelsBooking,
  ModelsBookingStats,
} from './..'

import { lasiusFetch } from '../../lasius-fetch-instance'

/**
 * @summary Get statistics about bookings for the selected project within the selected timeframe
 */
export type getProjectBookingListResponse200 = {
  data: ModelsBooking[]
  status: 200
}

export type getProjectBookingListResponseSuccess =
  getProjectBookingListResponse200 & {
    headers: Headers
  }
export type getProjectBookingListResponse = getProjectBookingListResponseSuccess

export const getGetProjectBookingListUrl = (
  orgId: string,
  projectId: string,
  params: GetProjectBookingListParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/organisations/${orgId}/projects/${projectId}/bookings/history?${stringifiedParams}`
    : `/organisations/${orgId}/projects/${projectId}/bookings/history`
}

export const getProjectBookingList = async (
  orgId: string,
  projectId: string,
  params: GetProjectBookingListParams,
  options?: RequestInit,
): Promise<getProjectBookingListResponse> => {
  return lasiusFetch<getProjectBookingListResponse>(
    getGetProjectBookingListUrl(orgId, projectId, params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export type getAggregatedStatisticsByProjectResponse200 = {
  data: ModelsBookingStats[]
  status: 200
}

export type getAggregatedStatisticsByProjectResponseSuccess =
  getAggregatedStatisticsByProjectResponse200 & {
    headers: Headers
  }
export type getAggregatedStatisticsByProjectResponse =
  getAggregatedStatisticsByProjectResponseSuccess

export const getGetAggregatedStatisticsByProjectUrl = (
  orgId: string,
  projectId: string,
  params: GetAggregatedStatisticsByProjectParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/organisations/${orgId}/projects/${projectId}/bookings/stats/aggregated?${stringifiedParams}`
    : `/organisations/${orgId}/projects/${projectId}/bookings/stats/aggregated`
}

export const getAggregatedStatisticsByProject = async (
  orgId: string,
  projectId: string,
  params: GetAggregatedStatisticsByProjectParams,
  options?: RequestInit,
): Promise<getAggregatedStatisticsByProjectResponse> => {
  return lasiusFetch<getAggregatedStatisticsByProjectResponse>(
    getGetAggregatedStatisticsByProjectUrl(orgId, projectId, params),
    {
      ...options,
      method: 'GET',
    },
  )
}
