import { lasiusFetch } from '../../lasius-fetch-instance'
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import {
	type ModelsAcceptInvitationRequest,
	type ModelsInvitation,
} from '.././'

export type getInvitationResponse =
	| getInvitationResponseError
	| getInvitationResponseSuccess

/**
 * @summary get detail of an invitation
 */
export type getInvitationResponse200 = {
	data: ModelsInvitation
	status: 200
}

export type getInvitationResponse400 = {
	data: void
	status: 400
}
export type getInvitationResponseError = getInvitationResponse400 & {
	headers: Headers
}

export type getInvitationResponseSuccess = getInvitationResponse200 & {
	headers: Headers
}

export const getGetInvitationUrl = (invitationId: string) => {
	return `/invitations/${invitationId}`
}

export const getInvitation = async (
	invitationId: string,
	options?: RequestInit,
): Promise<getInvitationResponse> => {
	return lasiusFetch<getInvitationResponse>(getGetInvitationUrl(invitationId), {
		...options,
		method: 'GET',
	})
}

export type acceptInvitationResponse = acceptInvitationResponseSuccess

export type acceptInvitationResponse200 = {
	data: ModelsInvitation
	status: 200
}

export type acceptInvitationResponseSuccess = acceptInvitationResponse200 & {
	headers: Headers
}

export const getAcceptInvitationUrl = (invitationId: string) => {
	return `/invitations/${invitationId}/accept`
}

export const acceptInvitation = async (
	invitationId: string,
	modelsAcceptInvitationRequest: ModelsAcceptInvitationRequest,
	options?: RequestInit,
): Promise<acceptInvitationResponse> => {
	return lasiusFetch<acceptInvitationResponse>(
		getAcceptInvitationUrl(invitationId),
		{
			...options,
			body: JSON.stringify(modelsAcceptInvitationRequest),
			headers: { 'Content-Type': 'application/json', ...options?.headers },
			method: 'POST',
		},
	)
}

export type declineInvitationResponse = declineInvitationResponseSuccess

export type declineInvitationResponse200 = {
	data: ModelsInvitation
	status: 200
}

export type declineInvitationResponseSuccess = declineInvitationResponse200 & {
	headers: Headers
}

export const getDeclineInvitationUrl = (invitationId: string) => {
	return `/invitations/${invitationId}/decline`
}

export const declineInvitation = async (
	invitationId: string,
	options?: RequestInit,
): Promise<declineInvitationResponse> => {
	return lasiusFetch<declineInvitationResponse>(
		getDeclineInvitationUrl(invitationId),
		{
			...options,
			method: 'POST',
		},
	)
}
