/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsFavoritesRequest, ModelsUserFavorites } from './..'

import { lasiusFetch } from '../../lasius-fetch-instance.ts'

export type getFavoriteBookingListResponse200 = {
  data: ModelsUserFavorites
  status: 200
}

export type getFavoriteBookingListResponseSuccess = getFavoriteBookingListResponse200 & {
  headers: Headers
}
export type getFavoriteBookingListResponse = getFavoriteBookingListResponseSuccess

export const getGetFavoriteBookingListUrl = (orgId: string) => {
  return `/user-favorites/organisations/${orgId}`
}

/**
 * @summary Get current user's favorite bookings list for the selected organisation
 */
export const getFavoriteBookingList = async (
  orgId: string,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<getFavoriteBookingListResponse> => {
  return lasiusFetch<getFavoriteBookingListResponse>(getGetFavoriteBookingListUrl(orgId), {
    ...options,
    method: 'GET',
  })
}

export type addFavoriteBookingResponse200 = {
  data: ModelsUserFavorites[]
  status: 200
}

export type addFavoriteBookingResponseSuccess = addFavoriteBookingResponse200 & {
  headers: Headers
}
export type addFavoriteBookingResponse = addFavoriteBookingResponseSuccess

export const getAddFavoriteBookingUrl = (orgId: string) => {
  return `/user-favorites/organisations/${orgId}`
}

/**
 * @summary Save a new favorite booking for the current user in the selected organisation
 */
export const addFavoriteBooking = async (
  orgId: string,
  modelsFavoritesRequest?: ModelsFavoritesRequest,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<addFavoriteBookingResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {}
    if (h instanceof Headers) return Object.fromEntries(h.entries())
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      )
    }
    const headers: Record<string, string | readonly string[]> = {}
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value
    }
    return headers
  }
  return lasiusFetch<addFavoriteBookingResponse>(getAddFavoriteBookingUrl(orgId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(modelsFavoritesRequest),
  })
}

export type deleteFavoriteBookingResponse200 = {
  data: void
  status: 200
}

export type deleteFavoriteBookingResponseSuccess = deleteFavoriteBookingResponse200 & {
  headers: Headers
}
export type deleteFavoriteBookingResponse = deleteFavoriteBookingResponseSuccess

export const getDeleteFavoriteBookingUrl = (orgId: string) => {
  return `/user-favorites/organisations/${orgId}`
}

/**
 * @summary Remove a favorite booking for the current user from the selected organisation
 */
export const deleteFavoriteBooking = async (
  orgId: string,
  modelsFavoritesRequest?: ModelsFavoritesRequest,
  options?: Parameters<typeof lasiusFetch>[1],
): Promise<deleteFavoriteBookingResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {}
    if (h instanceof Headers) return Object.fromEntries(h.entries())
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      )
    }
    const headers: Record<string, string | readonly string[]> = {}
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value
    }
    return headers
  }
  return lasiusFetch<deleteFavoriteBookingResponse>(getDeleteFavoriteBookingUrl(orgId), {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(modelsFavoritesRequest),
  })
}
