/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { ModelsEntityReference } from './modelsEntityReference'
import type { ModelsEntityReferenceModelsUserId } from './modelsEntityReferenceModelsUserId'

export interface ModelsOrganisation {
  id: string
  key: string
  private: boolean
  active: boolean
  createdBy: ModelsEntityReference
  deactivatedBy?: ModelsEntityReferenceModelsUserId | null
}
