/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { ModelsAuditInfoResponse } from './modelsAuditInfoResponse'
import type { ModelsConfigSyncStatus } from './modelsConfigSyncStatus'
import type { ModelsExternalProject } from './modelsExternalProject'
import type { ModelsGithubConfigResponseImporterType } from './modelsGithubConfigResponseImporterType'
import type { ModelsGithubConfigResponseResourceOwnerType } from './modelsGithubConfigResponseResourceOwnerType'
import type { ModelsGithubProjectMapping } from './modelsGithubProjectMapping'
import type { ModelsIssueImporterConfigId } from './modelsIssueImporterConfigId'

export interface ModelsGithubConfigResponse {
  id: ModelsIssueImporterConfigId
  importerType: ModelsGithubConfigResponseImporterType
  name: string
  baseUrl: string
  checkFrequency: number
  projects: ModelsGithubProjectMapping[]
  syncStatus: ModelsConfigSyncStatus
  audit: ModelsAuditInfoResponse
  /**
   * GitHub resource owner (organization or user login) for the token
   * @nullable
   */
  resourceOwner?: string | null
  /**
   * Type of the resource owner (User or Organization)
   * @nullable
   */
  resourceOwnerType?: ModelsGithubConfigResponseResourceOwnerType
  /**
   * List of available resource owners (user + organizations) for the token
   * @nullable
   */
  availableResourceOwners?: ModelsExternalProject[] | null
  type?: string
  projectCount: number
}
