/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { ModelsGithubTagConfiguration } from './modelsGithubTagConfiguration'
import type { ModelsGitlabTagConfiguration } from './modelsGitlabTagConfiguration'
import type { ModelsPlaneTagConfiguration } from './modelsPlaneTagConfiguration'

export interface ModelsUpdateProjectMapping {
  /** @nullable */
  externalProjectName?: string | null
  /** @nullable */
  gitlabProjectId?: string | null
  /** @nullable */
  projectKeyPrefix?: string | null
  gitlabTagConfig?: ModelsGitlabTagConfiguration | null
  /** @nullable */
  jiraProjectKey?: string | null
  /** @nullable */
  planeProjectId?: string | null
  planeTagConfig?: ModelsPlaneTagConfiguration | null
  /** @nullable */
  githubRepoOwner?: string | null
  /** @nullable */
  githubRepoName?: string | null
  githubTagConfig?: ModelsGithubTagConfiguration | null
  /** @nullable */
  maxResults?: number | null
  /** @nullable */
  params?: string | null
}
