/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { ModelsGithubProjectSettings } from './modelsGithubProjectSettings'
import type { ModelsProjectMappingId } from './modelsProjectMappingId'

export interface ModelsGithubProjectMapping {
  id: ModelsProjectMappingId
  projectId: string
  settings: ModelsGithubProjectSettings
}
