/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+154-fb40149e+20260327-1931
 */
import type { ModelsPlaneTagConfiguration } from './modelsPlaneTagConfiguration'

export interface ModelsPlaneProjectSettings {
  planeProjectId: string
  /** @nullable */
  externalProjectName?: string | null
  /** @nullable */
  maxResults?: number | null
  /** @nullable */
  params?: string | null
  tagConfiguration: ModelsPlaneTagConfiguration
}
