/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import type { ModelsTag, ModelsUpdateUserOrganisation, ModelsUser } from './..'

import { lasiusFetch } from '../../lasius-fetch-instance'

/**
 * @summary Change current user's working hours for the selected organisation
 */
export type updateWorkingHoursByOrganisationResponse200 = {
  data: ModelsUser
  status: 200
}

export type updateWorkingHoursByOrganisationResponseSuccess =
  updateWorkingHoursByOrganisationResponse200 & {
    headers: Headers
  }
export type updateWorkingHoursByOrganisationResponse =
  updateWorkingHoursByOrganisationResponseSuccess

export const getUpdateWorkingHoursByOrganisationUrl = (orgId: string) => {
  return `/user-organisations/organisations/${orgId}/working-hours`
}

export const updateWorkingHoursByOrganisation = async (
  orgId: string,
  modelsUpdateUserOrganisation: ModelsUpdateUserOrganisation,
  options?: RequestInit,
): Promise<updateWorkingHoursByOrganisationResponse> => {
  return lasiusFetch<updateWorkingHoursByOrganisationResponse>(
    getUpdateWorkingHoursByOrganisationUrl(orgId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsUpdateUserOrganisation),
    },
  )
}

/**
 * @summary Remove current user's membership from selected organisation
 */
export type deleteUserMembershipByOrganisationResponse200 = {
  data: void
  status: 200
}

export type deleteUserMembershipByOrganisationResponseSuccess =
  deleteUserMembershipByOrganisationResponse200 & {
    headers: Headers
  }
export type deleteUserMembershipByOrganisationResponse =
  deleteUserMembershipByOrganisationResponseSuccess

export const getDeleteUserMembershipByOrganisationUrl = (orgId: string) => {
  return `/user-organisations/organisations/${orgId}/leave`
}

export const deleteUserMembershipByOrganisation = async (
  orgId: string,
  options?: RequestInit,
): Promise<deleteUserMembershipByOrganisationResponse> => {
  return lasiusFetch<deleteUserMembershipByOrganisationResponse>(
    getDeleteUserMembershipByOrganisationUrl(orgId),
    {
      ...options,
      method: 'DELETE',
    },
  )
}

/**
 * @summary Get tags by organisation and project
 */
export type getTagsByProjectResponse200 = {
  data: ModelsTag[]
  status: 200
}

export type getTagsByProjectResponseSuccess = getTagsByProjectResponse200 & {
  headers: Headers
}
export type getTagsByProjectResponse = getTagsByProjectResponseSuccess

export const getGetTagsByProjectUrl = (orgId: string, projectId: string) => {
  return `/user-organisations/organisations/${orgId}/projects/${projectId}/tags`
}

export const getTagsByProject = async (
  orgId: string,
  projectId: string,
  options?: RequestInit,
): Promise<getTagsByProjectResponse> => {
  return lasiusFetch<getTagsByProjectResponse>(
    getGetTagsByProjectUrl(orgId, projectId),
    {
      ...options,
      method: 'GET',
    },
  )
}
