import { lasiusFetch } from '../../lasius-fetch-instance'
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import { type ModelsFavoritesRequest, type ModelsUserFavorites } from '.././'

export type getFavoriteBookingListResponse =
	getFavoriteBookingListResponseSuccess

/**
 * @summary Get current user's favorite bookings list for the selected organisation
 */
export type getFavoriteBookingListResponse200 = {
	data: ModelsUserFavorites
	status: 200
}

export type getFavoriteBookingListResponseSuccess =
	getFavoriteBookingListResponse200 & {
		headers: Headers
	}

export const getGetFavoriteBookingListUrl = (orgId: string) => {
	return `/user-favorites/organisations/${orgId}`
}

export const getFavoriteBookingList = async (
	orgId: string,
	options?: RequestInit,
): Promise<getFavoriteBookingListResponse> => {
	return lasiusFetch<getFavoriteBookingListResponse>(
		getGetFavoriteBookingListUrl(orgId),
		{
			...options,
			method: 'GET',
		},
	)
}

export type addFavoriteBookingResponse = addFavoriteBookingResponseSuccess

/**
 * @summary Save a new favorite booking for the current user in the selected organisation
 */
export type addFavoriteBookingResponse200 = {
	data: ModelsUserFavorites[]
	status: 200
}

export type addFavoriteBookingResponseSuccess =
	addFavoriteBookingResponse200 & {
		headers: Headers
	}

export const getAddFavoriteBookingUrl = (orgId: string) => {
	return `/user-favorites/organisations/${orgId}`
}

export const addFavoriteBooking = async (
	orgId: string,
	modelsFavoritesRequest: ModelsFavoritesRequest,
	options?: RequestInit,
): Promise<addFavoriteBookingResponse> => {
	return lasiusFetch<addFavoriteBookingResponse>(
		getAddFavoriteBookingUrl(orgId),
		{
			...options,
			body: JSON.stringify(modelsFavoritesRequest),
			headers: { 'Content-Type': 'application/json', ...options?.headers },
			method: 'POST',
		},
	)
}

export type deleteFavoriteBookingResponse = deleteFavoriteBookingResponseSuccess

/**
 * @summary Remove a favorite booking for the current user from the selected organisation
 */
export type deleteFavoriteBookingResponse200 = {
	data: void
	status: 200
}

export type deleteFavoriteBookingResponseSuccess =
	deleteFavoriteBookingResponse200 & {
		headers: Headers
	}

export const getDeleteFavoriteBookingUrl = (orgId: string) => {
	return `/user-favorites/organisations/${orgId}`
}

export const deleteFavoriteBooking = async (
	orgId: string,
	modelsFavoritesRequest: ModelsFavoritesRequest,
	options?: RequestInit,
): Promise<deleteFavoriteBookingResponse> => {
	return lasiusFetch<deleteFavoriteBookingResponse>(
		getDeleteFavoriteBookingUrl(orgId),
		{
			...options,
			body: JSON.stringify(modelsFavoritesRequest),
			headers: { 'Content-Type': 'application/json', ...options?.headers },
			method: 'DELETE',
		},
	)
}
