/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type { ModelsAcceptInvitationRequest, ModelsInvitation } from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
/**
 * @summary get detail of an invitation
 */
export function useGetInvitation(options?: ApiProxyOptions<ModelsInvitation>) {
  return useApiProxy<ModelsInvitation, undefined, { invitationId: string }>(
    {
      getUrl: ({ invitationId }) => `/invitations/${invitationId}`,
      method: 'GET',
    },
    options,
  )
}
export function useAcceptInvitation(options?: ApiProxyOptions<ModelsInvitation>) {
  return useApiProxy<ModelsInvitation, ModelsAcceptInvitationRequest, { invitationId: string }>(
    {
      getUrl: ({ invitationId }) => `/invitations/${invitationId}/accept`,
      method: 'POST',
    },
    options,
  )
}
export function useDeclineInvitation(options?: ApiProxyOptions<ModelsInvitation>) {
  return useApiProxy<ModelsInvitation, undefined, { invitationId: string }>(
    {
      getUrl: ({ invitationId }) => `/invitations/${invitationId}/decline`,
      method: 'POST',
    },
    options,
  )
}
