import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'

/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+137-fd682fb0+20260327-0053
 */
import { type ModelsInvitationStatusResponse } from '../../lasius'
/**
 * @summary get status of an invitation
 */
export function useGetInvitationStatus(
  options?: ApiProxyOptions<ModelsInvitationStatusResponse>,
) {
  return useApiProxy<
    ModelsInvitationStatusResponse,
    undefined,
    { invitationId: string }
  >(
    {
      getUrl: ({ invitationId }) => `/invitations/${invitationId}/status`,
      method: 'GET',
    },
    options,
  )
}
