/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+341-4c873927+20261007-1714
 */
import type {
  ModelsAcceptTOSRequest,
  ModelsPersonalDataUpdate,
  ModelsUser,
  ModelsUserSettings,
} from '../../lasius'

import { type ApiProxyOptions, useApiProxy } from '~/hooks/use-api-proxy'
/**
 * @summary Get current user's profile
 */
export function useGetUserProfile(options?: ApiProxyOptions<ModelsUser>) {
  return useApiProxy<ModelsUser>(
    {
      getUrl: () => `/user/profile`,
      method: 'GET',
    },
    options,
  )
} /**
 * The email is read-only. A request with a changed email answers 400 with the body email_read_only.
 * @summary Change current user's profile
 */
export function useUpdateUserProfile(options?: ApiProxyOptions<ModelsUser>) {
  return useApiProxy<ModelsUser, ModelsPersonalDataUpdate>(
    {
      getUrl: () => `/user/profile`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary Change current user's settings
 */
export function useUpdateUserSettings(options?: ApiProxyOptions<ModelsUser>) {
  return useApiProxy<ModelsUser, ModelsUserSettings>(
    {
      getUrl: () => `/user/profile/settings`,
      method: 'POST',
    },
    options,
  )
} /**
 * @summary Accept terms of service (TOS)
 */
export function useAcceptUserTOS(options?: ApiProxyOptions<ModelsUser>) {
  return useApiProxy<ModelsUser, ModelsAcceptTOSRequest>(
    {
      getUrl: () => `/user/accept-tos`,
      method: 'POST',
    },
    options,
  )
}
