name: Build frontend application

permissions:
  contents: read

on:
  workflow_call:
  workflow_dispatch:
  #pull_request:
  push:
    paths:
      - "frontend/**"
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build-frontend:
    name: Build frontend application for amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22
      - name: build frontend
        working-directory: ./frontend
        run: |
          npm --version
          yarn --version
          node ./scripts/updatePackageJsonVersion.js ${{github.ref_name}}
          yarn workspaces focus
          yarn run lint
          yarn run build
