name: Build & test backend application

permissions:
  contents: read

on:
  workflow_call:
  #pull_request:
  push:
    paths:
      - "backend/**"
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  Build-Backend:
    name: Build & test backend application
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Setup JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 25
      - name: Build backend
        working-directory: ./backend
        run: sbt clean update compile test dist
