name: Build & test backend application

permissions:
  contents: read

on:
  workflow_call:
  pull_request:
  push:
    paths:
      - "backend/**"
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  Build-Backend:
    name: Build & test backend application
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Setup JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: temurin
          java-version: 17
      - name: Build backend
        working-directory: ./backend
        run: sbt clean update compile test dist
