name: Build & test backend application

permissions:
  contents: read

on:
  workflow_call:
  #pull_request:
  push:
    paths:
      - "backend/**"
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  Build-Backend:
    name: Build & test backend application
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Setup JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: 17
      - name: Build backend
        working-directory: ./backend
        run: sbt clean update compile test dist
