name: Build & publish docker images

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    tags:
      - "**"

jobs:
  frontend:
    name: Build & push frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Add COMMIT_SHORT_SHA env property
        run: echo "COMMIT_SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - name: Login to DockerHub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push frontend image to docker hub
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc # v6.11
        with:
          context: "{{defaultContext}}:frontend"
          build-args: |
            LASIUS_VERSION=${{github.ref_name}}
          push: true
          tags: tegonal/lasius-frontend:${{github.ref_name}}

  backend:
    name: Build & push backend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Setup JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: 25
      - name: Add COMMIT_SHORT_SHA env property
        run: echo "COMMIT_SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push backend image to docker hub via sbt-native-packager
        working-directory: ./backend
        run: |
          # sbt-native-packager will compile, test, and build Docker image
          # The version is automatically set by git tag via dynver plugin
          sbt clean update compile test docker:publish
