import { lasiusFetch } from '../../lasius-fetch-instance'
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Lasius API
 * Track your time
 * OpenAPI spec version: 2.2.2+28-3680f9fd+20260321-0840
 */
import {
	type ModelsCreateOrganisation,
	type ModelsInvitationResult,
	type ModelsOrganisation,
	type ModelsUpdateOrganisation,
	type ModelsUserStub,
	type ModelsUserToOrganisationAssignment,
} from '.././'

export type createOrganisationResponse = createOrganisationResponseSuccess

/**
 * @summary create an organisation
 */
export type createOrganisationResponse201 = {
	data: ModelsOrganisation
	status: 201
}

export type createOrganisationResponseSuccess =
	createOrganisationResponse201 & {
		headers: Headers
	}

export const getCreateOrganisationUrl = () => {
	return `/organisations`
}

export const createOrganisation = async (
	modelsCreateOrganisation: ModelsCreateOrganisation,
	options?: RequestInit,
): Promise<createOrganisationResponse> => {
	return lasiusFetch<createOrganisationResponse>(getCreateOrganisationUrl(), {
		...options,
		body: JSON.stringify(modelsCreateOrganisation),
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		method: 'POST',
	})
}

export type getOrganisationResponse = getOrganisationResponseSuccess

export type getOrganisationResponse200 = {
	data: ModelsOrganisation
	status: 200
}

export type getOrganisationResponseSuccess = getOrganisationResponse200 & {
	headers: Headers
}

export const getGetOrganisationUrl = (orgId: string) => {
	return `/organisations/${orgId}`
}

export const getOrganisation = async (
	orgId: string,
	options?: RequestInit,
): Promise<getOrganisationResponse> => {
	return lasiusFetch<getOrganisationResponse>(getGetOrganisationUrl(orgId), {
		...options,
		method: 'GET',
	})
}

export type updateOrganisationResponse = updateOrganisationResponseSuccess

/**
 * @summary update an organisation
 */
export type updateOrganisationResponse200 = {
	data: ModelsOrganisation
	status: 200
}

export type updateOrganisationResponseSuccess =
	updateOrganisationResponse200 & {
		headers: Headers
	}

export const getUpdateOrganisationUrl = (orgId: string) => {
	return `/organisations/${orgId}`
}

export const updateOrganisation = async (
	orgId: string,
	modelsUpdateOrganisation: ModelsUpdateOrganisation,
	options?: RequestInit,
): Promise<updateOrganisationResponse> => {
	return lasiusFetch<updateOrganisationResponse>(
		getUpdateOrganisationUrl(orgId),
		{
			...options,
			body: JSON.stringify(modelsUpdateOrganisation),
			headers: { 'Content-Type': 'application/json', ...options?.headers },
			method: 'POST',
		},
	)
}

export type deactivateOrganisationResponse =
	deactivateOrganisationResponseSuccess

/**
 * @summary delete/deactivate an organisation
 */
export type deactivateOrganisationResponse200 = {
	data: void
	status: 200
}

export type deactivateOrganisationResponseSuccess =
	deactivateOrganisationResponse200 & {
		headers: Headers
	}

export const getDeactivateOrganisationUrl = (orgId: string) => {
	return `/organisations/${orgId}`
}

export const deactivateOrganisation = async (
	orgId: string,
	options?: RequestInit,
): Promise<deactivateOrganisationResponse> => {
	return lasiusFetch<deactivateOrganisationResponse>(
		getDeactivateOrganisationUrl(orgId),
		{
			...options,
			method: 'DELETE',
		},
	)
}

export type getOrganisationUserListResponse =
	getOrganisationUserListResponseSuccess

export type getOrganisationUserListResponse200 = {
	data: ModelsUserStub[]
	status: 200
}

export type getOrganisationUserListResponseSuccess =
	getOrganisationUserListResponse200 & {
		headers: Headers
	}

export const getGetOrganisationUserListUrl = (orgId: string) => {
	return `/organisations/${orgId}/users`
}

export const getOrganisationUserList = async (
	orgId: string,
	options?: RequestInit,
): Promise<getOrganisationUserListResponse> => {
	return lasiusFetch<getOrganisationUserListResponse>(
		getGetOrganisationUserListUrl(orgId),
		{
			...options,
			method: 'GET',
		},
	)
}

export type inviteOrganisationUserResponse =
	inviteOrganisationUserResponseSuccess

/**
 * @summary assign a user to an organisation
 */
export type inviteOrganisationUserResponse201 = {
	data: ModelsInvitationResult
	status: 201
}

export type inviteOrganisationUserResponseSuccess =
	inviteOrganisationUserResponse201 & {
		headers: Headers
	}

export const getInviteOrganisationUserUrl = (orgId: string) => {
	return `/organisations/${orgId}/invite`
}

export const inviteOrganisationUser = async (
	orgId: string,
	modelsUserToOrganisationAssignment: ModelsUserToOrganisationAssignment,
	options?: RequestInit,
): Promise<inviteOrganisationUserResponse> => {
	return lasiusFetch<inviteOrganisationUserResponse>(
		getInviteOrganisationUserUrl(orgId),
		{
			...options,
			body: JSON.stringify(modelsUserToOrganisationAssignment),
			headers: { 'Content-Type': 'application/json', ...options?.headers },
			method: 'POST',
		},
	)
}

export type removeOrganisationUserResponse =
	removeOrganisationUserResponseSuccess

/**
 * @summary Remove selected user's membership from selected organisation
 */
export type removeOrganisationUserResponse200 = {
	data: void
	status: 200
}

export type removeOrganisationUserResponseSuccess =
	removeOrganisationUserResponse200 & {
		headers: Headers
	}

export const getRemoveOrganisationUserUrl = (orgId: string, userId: string) => {
	return `/organisations/${orgId}/users/${userId}`
}

export const removeOrganisationUser = async (
	orgId: string,
	userId: string,
	options?: RequestInit,
): Promise<removeOrganisationUserResponse> => {
	return lasiusFetch<removeOrganisationUserResponse>(
		getRemoveOrganisationUserUrl(orgId, userId),
		{
			...options,
			method: 'DELETE',
		},
	)
}
